### ISSUE TITLE
Form attribute size is limited to 1024 in Vert.x 4

### ISSUE THREAD

**Issue by pavelarnost** [eclipse-vertx/vert.x#3794] opened 2021-02-08 11:40 UTC
### Version

4.0.2

### Context

Processing of forms with large attribute values is not possible in Vert.x 4 because maximum attribute size is hardcoded to 1024 in NettyFileUploadDataFactory / VertxAttribute class. It works without problems in Vert.x 3.9.5 or when setMaxSize() argument is changed to bigger value.

**Comment by vietj** [comment] 2021-02-08 11:58
@pavelarnost we should make this a configurable option in HTTP server options or HTTP server request I think

**Comment by st-h** [comment] 2021-02-27 12:52
I just spent a day trying to figure out why a request to a simple vertx server would result in a http 400 returned by the web client. Turns out this arbitrary limitation is the case.

Please add a clear error message when this limitation has been hit, instead of failing the request silently and returning a http 400 response status. This makes it so difficult to find out what is going on.

Please also add those limitations and changes to the upgrade docs. Uprading to vert.x 4 turns out to be a real hassle due to crucial things are not mentioned at all or only very vaguely. Like an auth handler needs to pause the incoming request, while doing async stuff. Or this limitation here. Going to fix the CORS bugs myself in vertx 3.9.5 and stop upgrading to vert.x 4 for now, because vert.x 4 doesn't feel production ready at all at the moment.

**Comment by st-h** [comment] 2021-02-27 15:03
I have just been trying to upgrade to vertx 3.9.6 and I seem to encounter the exact same issue

**Comment by st-h** [comment] 2021-02-27 15:06
Btw: I have written a simple Spock test together with a simple vertx server that reproduces the issue. It's not in a separate project, but I can add those classes here if there is any need for them.

**Comment by vietj** [comment] 2021-03-01 06:45
this has been made configurable in 3.9.6 and upcoming 4.0.3 - https://github.com/eclipse-vertx/vert.x/issues/3826

**Comment by vietj** [comment] 2021-03-11 09:43
this has been fixed in master and the default value is set to 2K instead of 1K.

**Closed by vietj** 2021-03-11 09:43 UTC
Labels: bug
