### ISSUE TITLE
Pause is not respected

### ISSUE THREAD

**Issue by dave-fl** [eclipse-vertx/vert.x#2895] opened 2019-04-03 17:26 UTC
It does not appear that Pause has any impact at all on whether or not a stream is paused.

In the example, the Flowable chain will perform two read request on the webclient prior to reading the inbound stream and when the stream is read an error is produced that the stream has already been read.

Using version 3.7.0.

[Reproducer](https://github.com/dave-fl/ignore-pause/blob/master/src/main/java/com/example/verticles/IgnorePause.java)

	java.lang.IllegalStateException: Request has already been read
		at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:607)
		at io.vertx.core.http.impl.HttpServerRequestImpl.endHandler(HttpServerRequestImpl.java:364)
		at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:64)
		at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:16)
		at io.vertx.reactivex.impl.FlowableReadStream.subscribeActual(FlowableReadStream.java:74)
		at io.reactivex.Flowable.subscribe(Flowable.java:14805)
		at io.reactivex.Flowable.subscribe(Flowable.java:14752)
		at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
		at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
		at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:62)
		at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:52)
		at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:586)
		at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:583)
		at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285)
		at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272)
		at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
		at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
		at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
		at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
		at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
		at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218)
		at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341)
		at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
		at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment] 2019-04-03 17:44
ok I see more clearly what you mean now.

with RX, vertx-rx will fully manage the ReadStream and pause/resume it according to the demand of the Flowable.

so you should not mix both because it will introduce bugs.

if you want to pause/resume the stream, then you should defer the call to toFlowable() until you are done using manual pause/resume.

**Comment by dave-fl** [comment] 2019-04-03 18:48
Sorry @vietj but I don't fully understand.  Are you saying that if I am using RX world than I should never use pause/resume?  

If I remove pause in the above case, I still get the same error.  Should I be starting the RX change somewhere else?

**Comment by dave-fl** [comment] 2019-04-03 19:11
This fails as well and it is only Rx.  Is it safe to say that one must always subscribe to the request stream as soon as possible.

		httpServer.requestStream().toFlowable().subscribe(serverRequest -> {
		webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse -> {
			logger.info(bufferHttpResponse.bodyAsString());
			return webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse1 -> {
				logger.info(bufferHttpResponse.bodyAsString());
				return serverRequest.toFlowable();
			});
		}).subscribe(buffer -> {
			serverRequest.response().write(buffer);
		}, throwable -> {
			logger.error("Error", throwable);
			serverRequest.response().setStatusCode(500);
			serverRequest.response().end();
		}, () -> {
			serverRequest.response().setStatusCode(200);
			serverRequest.response().end();
		});
	});

**Comment by vietj** [comment] 2019-04-03 22:06
actually now I looked at your code, I think this is an issue coming from vertx-rx that pause the stream too late at subscription time and I think it should be done in the `toFlowable()` method.

**Comment by vietj** [comment] 2019-04-03 22:07
so I think it's not a vertx-core issue but rather a vertx-rx issue

**Comment by vietj** [comment] 2019-04-03 22:08
can you open an issue with a reproducer in vertx-rx project ?

**Comment by vietj** [comment] 2019-04-03 22:08
I will close this one.

**Closed by vietj** 2019-04-03 22:08 UTC

**Comment by vietj** [comment] 2019-04-03 22:10
as workaround what you can do is manually pause the `serverRequest`  so it does not end

```
        serverRequest.pause(); // Explicitely pause the stream here
	serverRequest.response().setChunked(true);
```

I misunderstood your case initially.

Currently the stream pause is deferred by RxJava with your pipeline and as I said likely the stream pause should be done ahead of time in the `toFlowable()` method instead.

**Comment by dave-fl** [comment] 2019-04-04 03:31
@vietj I immediately pause, how is that different?
