### ISSUE TITLE
4.0.0-milestone4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by joggerjoel** [eclipse-vertx/vert.x#3404] opened 2020-05-10 22:22 UTC
### Questions

ERROR io.vertx.core.impl.ContextImpl - Unhandled exception

### Version

vert.x 4.0.0-milestone

uname -a | Linux ventech 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a | Ubuntu 18.04.4 LTS bionic

### Context

I encountered an exception which looks suspicious while unit testing on Ubuntu; however it works fine using macOS Catalina Version 10.15.4

### Do you have a reproducer?
https://github.com/joggerjoel/codeone-conduit

### Steps to reproduce

1. using both java8 and java11 openjdk to test issue
2. mvn clean; mvn package

### Extra

```
16:54:29.053 [vert.x-eventloop-thread-8] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:981) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:388) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:381) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:880) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:42) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.EventLoopContext.dispatch(EventLoopContext.java:77) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.EventLoopContext.dispatch(EventLoopContext.java:65) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:149) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.Promise.complete(Promise.java:67) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.DeploymentManager.lambda$null$4(DeploymentManager.java:227) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.EventLoopContext.dispatch(EventLoopContext.java:72) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.EventLoopContext.dispatch(EventLoopContext.java:65) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.FutureImpl.onComplete(FutureImpl.java:97) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.Future.setHandler(Future.java:109) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:210) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.vertx.core.impl.EventLoopContext.lambda$execute$0(EventLoopContext.java:42) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-common-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.42.Final.jar:4.1.42.Final]
        at 
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.42.Final.jar:4.1.42.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by tsegismont** [comment] 2020-05-12 05:35
I tried to build the project with the given instructions, it passed successfully. But this is because the test is implemented with junit4 while the POM has both junit4 and junit5 dependencies. Consequently, the Maven surefire plugin is confused and finds no test at all.

Can you rework your reproducer please? Also, add instructions to start Mongo and add minimal required data. Otherwise it's impossible to reproduce the issue.

**Comment by vietj** [comment] 2020-05-12 07:11
is this a mongo issue ?

**Comment by joggerjoel** [comment] 2020-05-13 15:23
Here are the steps to install Mongo on Ubuntu 18.04. I will try to remove mongo and remove the junit4 since I upgraded to junit5.

Once Mongo runs, the app will create the schema/data accordingly.

https://docs.google.com/spreadsheets/d/1hWLoQCMHv1IFJHAxxAzaQt-oq-pdYGXnAtjEyn5VD6w/edit?usp=sharing

**Comment by joggerjoel** [comment] 2020-05-13 15:30
It appears to breaking with log4j2

2020-05-13 10:28:56,902 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=jar:file:/home/joggerjoel/Documents/Projects/demo/codeone-conduit-4.0.0-build4-nomongo/target/vertx-codeone-conduit-1.0-SNAPSHOT-fat.jar!/log4j2.xml] OK
2020-05-13 10:28:56,902 pool-1-thread-1 DEBUG Stopped LoggerContext[name=74a14482, org.apache.logging.log4j.core.LoggerContext@1e6454ec] with status true

**Comment by joggerjoel** [comment] 2020-05-13 15:52
@tsegismont I have updated the https://github.com/joggerjoel/codeone-conduit/tree/master to your request. Also, if I remove mongo manually, the tests do pass with no exception.

One issue you should be aware, if using log4j2 on ubuntu 18.04; I had to copy my .m2 from macos as for some reason it doesn't download automatically.

https://issues.apache.org/jira/browse/LOG4J2-2842

**Comment by joggerjoel** [comment] 2020-05-13 21:04
I tested from Ubuntu 18.04 Java Client -> MacOS MongoDB-community@4.2 and java.util.concurrent.RejectedExecutionException: event executor terminated still occurs.

**Comment by joggerjoel** [comment] 2020-05-14 13:25
line 83: loginAuthProvider.insertUser

**Comment by joggerjoel** [comment] 2020-05-15 14:15
Compiled on Ubuntu Focal 20.02; it works fine..

**Comment by tsegismont** [comment] 2020-05-25 15:53
@joggerjoel I'm going to close this issue as it doesn't seem like a Vert.x core issue.

To move forward, please put all the reproduction steps in the README of the GitHub project and share the issue on the Vert.x forum.

You have greater chances to get replies if the instructions are concise and repeatable for everyone (not just the developers who have a Mac).

**Closed by tsegismont** 2020-05-25 15:53 UTC
Labels: question
