### ISSUE TITLE
Unmaintained or buggy cluster managers need to be removed

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3485] opened 2020-07-07 02:45 UTC
### Version

`vertx-core:3.9.1`

### Context

My application uses locks with long timeouts and may scale up and down. Previously, I used a forked version of [`AtomixClusterManager`](https://github.com/atomix/atomix-vertx/blob/master/src/main/java/io/atomix/vertx/AtomixClusterManager.java) brought into my tree. `atomix` appears to have the best API and cleanest semantics for clustering.

However, `atomix` appears to have a showstopping bug (see https://github.com/atomix/atomix/issues/1077) that I reproduced when doing integration tests with my app. Long ago, I had tried the Hazelcast cluster manager, but it had many mysterious issues, sometimes related to `vertx-sync`, sometimes bugs, and sometimes performance regressions.

Today, I tried migrating to both `vertx-zookeeper:3.9.1` and `vertx-ignite:3.9.1`, neither of which worked.

 - `vertx-zookeeper` issues:
     - It uses an out of date version of `org.apache.curator` and `org.apache.zookeeper`, bringing in Netty 3. This has been fixed for 3 years.
     - It has bugs like https://github.com/vert-x3/vertx-zookeeper/issues/100 and https://github.com/vert-x3/vertx-zookeeper/issues/99
     - It does not appear that locks by the same name can be waited on concurrently, regardless of how many internal event loop threads are made.
 - `vertx-ignite` issues:
     - It also uses a version of Ignite so out of date it does not run on Java 11.
     - `ignite` TCP discovery does not work when two or more instances are started simultaneously on the same JVM, a normal thing to attempt in an integration test.
     - Its locks implementation is really badly broken.

I know you are migrating to a new SPI. So maybe that will help. But overall I think the cluster managers are falling into disrepair. You may consider adopting something like `atomix` or building on top of `etcd` (like everyone else) and just fixing it as a standard feature.

**Comment by tsegismont** [comment] 2020-07-07 13:20
As you may know, the Atomix cluster manager is not part of the Vert.x stack. So I can't say anything about it. In fact, I wasn't aware of its existence.

I don't know when you stopped using `vertx-hazelcast`, but we have received many bug reports that were fixed.

We also have `vertx-infinispan` in the stack, which has been used by an increasing number of users.

The `vertx-zookeeper` maintainer has not yet provided an update to `master` following the clustering SPI update. If we don't get it in time we may consider releasing Vert.x 4.0 without `vertx-zookeeper`. Nevertheless, we are still committed to address issues in the 3.9 branch.
I will take care of the `removeIfPresent` implementation. Thanks for reporting it.
The issue with the cache name containing a slash seems to be a limitation of the implementation. Not sure if we can do anything about it.

Vert.x Ignite has been upgraded to a recent version in `master` (Vert.x 4.0). It works with the new clustering SPI. These changes are present in the Vert.x 4 milestone5 release.
Our test suite starts several instances in the same JVM so I'm not sure what's the problem you found. Can file an issue with a reproducer?

**Comment by tsegismont** [comment] 2020-07-07 13:23
Closing as this is not related to Vert.x core. Please follow-up in the issues linked above or file new ones in the corresponding cluster manager repository with a reproducer.

**Closed by tsegismont** 2020-07-07 13:23 UTC
Labels: question

**Comment by vietj** [comment] 2020-07-07 14:29
thank you Thomas
