### ISSUE TITLE
http chunked response with buffer slices served over TLS corrupts input data

### ISSUE THREAD

**Issue by conet** [eclipse-vertx/vert.x#4509] opened 2022-10-18 08:06 UTC
### Version

4.3.4

### Context

While working on a streaming http server I encountered data corruption if TLS was used, this did not happen if TLS was not present. As far as I can tell buffers sent as response should be considered read only so I consider this alteration of buffer contents as a bug. If this was not true it means that the data delivered on every response must be copied which is a huge performance issue.

### Do you have a reproducer?

The reproducer contains all the details.

https://github.com/conet/vertx-tls-reproducer

### Steps to reproduce

1. Run the test with TLS enabled
2. Compare the input file with the output file
3. The actual result is that the files are different
4. The files should be identical
5. All diff instances involve http chunked encoding protocol data `0D 0A 66 61 30 0D 0A` -> `CR LF size CR LF` which means that the chunked encoding protocol corrupts the input buffer (emitted in slices - read only references pointing to the same underlying buffer)
6. This does not happen when TLS is disabled

### Extra

Might be caused by something like [this](https://github.com/netty/netty/issues/11792)

**Comment by conet** [comment] 2022-10-19 10:06
I found out that if I transform the source buffers into a read only buffers like this:
```
.map(buffer -> Buffer.buffer(buffer.getByteBuf().asReadOnly()))
```
The corruption does not happen anymore. This is a solution that we can work with because sharing a read only buffer stream is really what we were looking for.

**Comment by vietj** [comment] 2022-10-19 13:48
vertx buffers can be shared only if they are not modified, usually sending buffer on a response should not modify them unless there is a bug (e.g like you pointed out there was in netty). 

Can you try using a specific implementation of netty ByteBuf that logs when the buffer is actually (with a stacktrace) modified, instead of being read-only ?

**Comment by conet** [comment] 2022-10-19 14:45
I [tried it](https://github.com/conet/vertx-tls-reproducer/commit/602caa2f72335422d33374c1b100cc6e8c933623) but it didn't work, looks like the write does not go through the implementation that calls `ensureWritable` or maybe I'm missing something.

**Comment by vietj** [comment] 2022-10-20 13:59
thanks for your investigation work @conet , can we reproduce this with a smaller reproducer (i.e with a minimum amount of data) ?

**Comment by vietj** [comment] 2022-10-20 14:31
what is not clear to me with respect to the netty issue that is referenced is that

- in the netty bug, the byte buf were corrupted because they are shared
- in this case buffers are not shared since they originate from the file system

so I do not understand yet how the bug happens if the byte buf originating from the file system can be expanded

**Comment by vietj** [comment] 2022-10-20 14:34
ah I think I understand what I was missing : it comes from the slice operation that is performed in the `concatMap` that shares the same underlying bigger byte buf.

**Comment by vietj** [comment] 2022-10-20 14:51
so here is what happen:

- the concatMap will slice vertx buffers that create netty slices, normally those buffers cannot be appended to
- when such buffers are written to the `HttpServerResponse`, they are duplicated (so the netty slice is duplicated) and the duplicate does not respect the slice nature of the buffer, making the buffer appendable

e.g let's take this vertx code

```java
    Buffer hello_world = Buffer.buffer("Hello World");
    Buffer hello = hello_world.slice(0, 5); // create a Netty slice
    hello.getByteBuf().writeByte('_'); // getByteBuf duplicates the bytebuf which is  a slice, it is duplicated as a regular byte buf and we get Hello_World which should not be possible
    ((BufferImpl)hello).byteBuf().writeByte(' '); // bytebuf() returns the original buffer, throws an exception because we are using a slice
```

**Comment by vietj** [comment] 2022-10-20 15:01
wondering first whether the netty slice duplicate should not itself duplicate into a slice as well, or vertx should ensure the correctness

**Comment by conet** [comment] 2022-10-20 15:03
That is a good question, if you think that vert.x uses netty correctly then the problem is in netty otherwise it's a problem vert.x needs to fix.

**Comment by vietj** [comment] 2022-10-20 15:06
I don't think read only is involved here, a slice is writable, however it cannot be expanded which cause the issue with SSL handler.

**Comment by conet** [comment] 2022-10-20 15:08
OK, I'm not that familiar with all netty buffer attributes, I was thinking read only because making the underlying buffer (the one that is sliced) read only fixes the problem.

**Comment by conet** [comment] 2022-10-20 15:16
Yes, I think that would work, that is also the check used by `SSLHandler`.

**Comment by vietj** [comment] 2022-10-20 15:34
that sound more complex than at first sight, I'm having a look but in reality a sliced buffer has an adjustment field (offset) and it is not possible to know this adjustment field when we use a slice, which means that a vertx sliced buffer should retain the original information when a slice operation happens in vertx I think.

**Comment by vietj** [comment] 2022-10-20 16:51
I'll provide a patch soon and check against the reproducer you provided @conet

**Comment by vietj** [comment] 2022-10-21 08:00
created this issue to check whether that's considered as a ByteBuf defect : https://github.com/netty/netty/issues/12919

**Comment by vietj** [comment] 2022-10-24 08:40
it is not considered as a defect, I believe one way we can do it, is simply by replacing the `duplicate` by a `slice`, so vertx buffers will always send slices through the pipeline which will always prevent the buffers to be appended to.

**Comment by vietj** [comment] 2022-10-25 08:04
fixed by https://github.com/eclipse-vertx/vert.x/issues/4517

**Closed** 2022-10-25 08:04 UTC
Labels: bug
