### ISSUE TITLE
Connection not closed after exception in HTTP client request

### ISSUE THREAD

**Issue by gilhod** [eclipse-vertx/vert.x#4465] opened 2022-08-25 21:34 UTC
### Version

4.2.7

### Context

When there is an exception after connection was established (HttpClient.request), but before the request was sent (HttpClientRequest.send), the connection is not closed immediately, but it waits for idle timeout to be reached (either from server or client), and only then the connection is closed and the request fails on triggered exception. If no idle timeout is set, on server and client, the connection will wait forever. If number of exceptions exceed the number of allowed open connections, subsequent requests will wait for connection forever.

What I don't understand is why waiting for the idle timeout, if we already know that the request failed.
There is no way to detect that failure and fail the request in real time?

The solutions I've found to handle this is to add try/catch and close the connection by myself when I catch the exception.

### Reproducer

https://github.com/gilhod/ConnectionNotClosed

### Steps to reproduce

1. Run the ServerApp
2. Run the ClientApp and notice that: 
    - Connections are not closed
    - after five requests, no further requests are handled 
5. Rerun ClientApp, with idleTimeout = 10, and notice that connection is closed after that 10 seconds
6. Run ClientWithFix, and notice connections are closed and all requests handled immediately

**Comment by vietj** [comment] 2022-09-13 07:16
this is expected and how things are supposed to behave.

since the code using the client has a fault and indeed if there is an exception you should release the resource, like you do with any resource (e.g an open file).

this client provides fine grained interactions with multi step to perform a request/response, if you need a client that is simpler, then you should instead use the web client (https://vertx.io/docs/vertx-web-client/java/).

note : in your reproducer the best would be to use `request.reset()` instead of closing the connection, because closing the connection is incorrect when using HTTP/2

**Closed by vietj** 2022-09-13 07:16 UTC
Labels: bug
