### ISSUE TITLE
ALPN not available for JDK SSL/TLS engine

### ISSUE THREAD

**Issue by wujun** [eclipse-vertx/vert.x#3387] opened 2020-04-23 17:47 UTC
I created a simple grpc application with ssl on vertx  but got error (my mac osx:v10.14.16, openssl : v1.1.1f, vertx 3.9.0)
the sample code:
    VertxServer rpcServer = VertxServerBuilder.
      forAddress(vertx, "localhost", 443).
      addService(service).
      useSsl(opt ->
        opt.setSsl(true).setUseAlpn(true).setKeyStoreOptions(
          new JksOptions().setPath("tls/server-keystore.jks").setPassword("wibble"))
      ).
      build();

    rpcServer.start(ar -> {
      if (ar.succeeded()) {
        System.out.println("RPC server started!");
      }
      else {
        System.out.println("Could not start server " + ar.cause().getMessage());
      }
    });

the jks file is copied from vertx-examples and pom.xml looks like below(I just modified some senseitive info):

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.xxx</groupId>
  <artifactId>yyy</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>

    <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
    <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
    <maven-surefire-plugin.version>2.22.1</maven-surefire-plugin.version>
    <exec-maven-plugin.version>1.5.0</exec-maven-plugin.version>

    <vertx.version>3.9.0</vertx.version>
    <junit-jupiter.version>5.4.0</junit-jupiter.version>

    <main.verticle>org.xxx.yyy.MainVerticle</main.verticle>
    <vertx.grpc.version>1.16.1</vertx.grpc.version>
    <jetty.alpnAgent.version>2.0.7</jetty.alpnAgent.version>
    <os.detected.classifier>osx-x86_64</os.detected.classifier>
    <jetty.alpnAgent.path>${settings.localRepository}/org/mortbay/jetty/alpn/jetty-alpn-agent/${jetty.alpnAgent.version}/jetty-alpn-agent-${jetty.alpnAgent.version}.jar</jetty.alpnAgent.path>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-stack-depchain</artifactId>
        <version>${vertx.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-grpc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.binance.api</groupId>
      <artifactId>binance-api-client</artifactId>
      <version>1.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit-jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit-jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
      <version>3.5.1</version>
      <exclusions>
        <exclusion>
          
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.29.Final</version>
    </dependency>
    <dependency>
      <groupId>org.mortbay.jetty.alpn</groupId>
      <artifactId>jetty-alpn-agent</artifactId>
      <version>${jetty.alpnAgent.version}</version>
    </dependency>
  </dependencies>

  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.4.1.Final</version>
      </extension>
    </extensions>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <argLine> -javaagent:${jetty.alpnAgent.path}</argLine>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.5.0</version>
        <configuration>
          
          <protocArtifact>com.google.protobuf:protoc:3.4.0:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.vertx:protoc-gen-grpc-java:1.25.0:exe:${os.detected.classifier}</pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <id>compile</id>
            <configuration>
              <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
              <clearOutputDirectory>false</clearOutputDirectory>
            </configuration>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
              <goal>test-compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>${maven-shade-plugin.version}</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <manifestEntries>
                    <Main-Class>io.vertx.core.Launcher</Main-Class>
                    <Main-Verticle>${main.verticle}</Main-Verticle>
                  </manifestEntries>
                </transformer>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/services/io.vertx.core.spi.VerticleFactory</resource>
                </transformer>
              </transformers>
              <artifactSet>
              </artifactSet>
              <outputFile>${project.build.directory}/${project.artifactId}-${project.version}-fat.jar
              </outputFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>${exec-maven-plugin.version}</version>
        <configuration>
          <mainClass>io.vertx.core.Launcher</mainClass>
          <arguments>
            <argument>run</argument>
            <argument>${main.verticle}</argument>
          </arguments>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>

**Comment by vietj** [comment] 2020-04-23 18:17
so what's the failure ? which JDK are you using ?

**Comment by vietj** [comment] 2020-04-23 18:17
do you  have a proper stack trace to show ?

**Comment by wujun** [comment] 2020-04-24 07:58
Thanks a lot, the failure is below and my JDK is 1.8:
io.vertx.core.VertxException: ALPN not available for JDK SSL/TLS engine
	at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:88)
	at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:155)
	at io.vertx.grpc.VertxServer$ActualServer.<init>(VertxServer.java:53)
	at io.vertx.grpc.VertxServer$ActualServer.<init>(VertxServer.java:39)
	at io.vertx.grpc.VertxServer.lambda$start$1(VertxServer.java:137)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.vertx.grpc.VertxServer.start(VertxServer.java:137)
	at org.xxx.yyy.MainVerticle.start(MainVerticle.java:57)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment] 2020-04-24 09:11
which JDK version ?

java -version

**Comment by wujun** [comment] 2020-04-24 14:56
Sorry, the detail about jdk version is:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by wujun** [comment] 2020-04-25 08:16
[binanceBot3.8.5.zip](https://github.com/eclipse-vertx/vert.x/files/4532605/binanceBot3.8.5.zip)
This is my simple project created on IntelliJ idea (2020.1). It also has the same problem! Thanks

**Comment by vietj** [comment] 2020-04-25 09:30
I cannot test your project @wujun because `Could not find artifact com.binance.api:binance-api-client:jar:1.0.1`

**Comment by vietj** [comment] 2020-04-25 09:30
note that very recent versions of OpenJDK do actually provide ALPN support (it was backported) and will not currently work with Vert.x (nor Netty) and we will do an update soon for this. I'll open an issue to track it down.

**Comment by vietj** [comment] 2020-04-25 09:34
See https://github.com/eclipse-vertx/vert.x/issues/3391 and check if your OpenJDK version falls in this category.

**Comment by wujun** [comment] 2020-04-25 16:19
> I cannot test your project @wujun because `Could not find artifact com.binance.api:binance-api-client:jar:1.0.1`

Thank you very much, about my project code, just remove this  dependency without any hesitation if you want to reproduce this problem:0

**Comment by daniel-farkas** [comment] 2020-10-07 19:04
Any news on this? I'm having the same issue, running Vert.x  3.9.1 and OpenJDK 1.8.0_252.
I tried forcing Netty version to 4.1.49.Final, but it didn't help.

**Comment by kissLife** [comment] 2020-10-11 04:27
use the correct version netty-tcnative-boringssl-static dependency. see also [this link](https://stackoverflow.com/questions/44822214/vert-x-http-2-alpn-not-available-for-jdk-ssl-tls-engine).

**Comment by daniel-farkas** [comment] 2020-10-15 00:33
That doesn't help at all. I have no direct dependency to Netty or its subpackages. When I add
```
compile("io.netty:netty-tcnative-boringssl-static:2.0.25.Final"){force = true}
```
or any variant of it, nothing new happens. I still get
```
2020-10-15 00:28:53,454 ERROR io.vertx.core.impl.DeploymentManager:505 - ALPN not available for JDK SSL/TLS engine
io.vertx.core.VertxException: ALPN not available for JDK SSL/TLS engine
```

**Comment by vietj** [comment] 2021-02-23 09:02
@daniel-farkas we just did a test and it works, can you provide a reproducer ?

**Comment by vietj** [comment] 2021-02-23 09:04
you can also set a Java breakpoint in JdkSSLEngineOptions#isAlpnAvailable()` method and examine why this method returns false. That would help a lot resolving this issue.

in the meantime I'll close this issue and we should reopen if there is an actual bug with your current JDK.

**Closed by vietj** 2021-02-23 09:04 UTC
Labels: bug
