### ISSUE TITLE
Vert.x doesn't handle Transfer-Encoding properly

### ISSUE THREAD

**Issue by cristianokbc** [eclipse-vertx/vert.x#3353] opened 2020-04-01 18:22 UTC
### Version

3.8.5

### Context

When a client sends "Transfer-Encoding: gzip, chunked", Vert.x resets the client connection without sending a response.

### Do you have a reproducer?

https://github.com/cristianokbc/vertx-starter

### Steps to reproduce

1. Clone the repository https://github.com/cristianokbc/vertx-starter
2. Start it using `mvn clean compile java:exec`
3. Make a POST request using the following curl command:
```sh
curl http://localhost:8888 -H "Transfer-Encoding: gzip, chunked" -d @./data.gz -X POST -v
```

The client will be disconnected without any response:

```
* About to connect() to localhost port 8888 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8888
> Accept: */*
> Transfer-Encoding: gzip, chunked
> Content-Type: application/x-www-form-urlencoded
> 
> 8
* upload completely sent off: 15 out of 8 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by tsegismont** [comment] 2020-05-14 10:11
Could you please add the file in the reproducer? What kind of content is it? Form data? Binary?

**Comment by gaol** [comment] 2020-05-26 07:11
It looks like using the `tar -czvf data.gz README.adoc` can reproduce the issue(reproduced in master as well). I believe it has something with netty's decoding on the chunked request.  

@tsegismont May I take a look at this issue?  :smile:

**Comment by tsegismont** [comment] 2020-05-26 08:12
@gaol of course, thanks for looking into this!

**Comment by gaol** [comment] 2020-05-27 02:24
@tsegismont @cristianokbc I have opened a netty issue https://github.com/netty/netty/issues/10320 with a proposed PR: https://github.com/netty/netty/pull/10321, it will sove this issue too.

**Comment by tsegismont** [comment] 2020-05-27 05:50
Thank you!

**Comment by gaol** [comment] 2020-06-07 01:24
https://github.com/netty/netty/pull/10321 was merged, this issue should be fixed when we upgrade netty to  4.1.51.Final once it is released.

**Comment by vietj** [comment] 2020-06-07 09:31
thanks @gaol

**Comment by vietj** [comment] 2020-07-01 14:55
Netty 4.1.51.Final does not seem released yet.

**Comment by k-mack** [comment] 2020-07-13 14:34
Netty 4.1.51.Final was released (see https://github.com/netty/netty/releases/tag/netty-4.1.51.Final).

**Comment by tsegismont** [comment] 2021-01-18 09:21
@vietj you just closed https://github.com/vert-x3/issues/issues/552

I guess the Netty upgrade won't be backported to 3.9 so can we change the milestone of this issue to 4.0.1 and close?

**Comment by vietj** [comment] 2021-01-18 09:22
yes we will likely also back port to 3.9 as this is a Netty upgrade

**Comment by vietj** [comment] 2021-01-18 09:23
the issue is how do we properly handle a same fix in 2 branches we maintain

**Comment by vietj** [comment] 2021-01-18 09:23
for now let's scope this to 4.0.1 and close it.

**Closed by vietj** 2021-01-18 09:23 UTC
Labels: bug
