### ISSUE TITLE
Doubled paths using the file resolver on Windows

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#3372] opened 2020-04-14 06:06 UTC
See:
https://github.com/quarkusio/quarkus/pull/8518

On windows, something has changed in the file resolver between 3.8.5 and 3.9.0:
```
2020-04-11T08:12:02.1127183Z 2020-04-11 08:12:02,096 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /abc/not_found failed, error id: 8d6f8a61-e0f1-4141-9fbe-0b54e7e5cc50-1: java.nio.file.InvalidPathException: Illegal char <:> at index 120: D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\vertx-cache\file-cache-93439211-4463-4880-bc3e-6fd8101e95a4\D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test9360317579511630399\src\main\resources\META-INF\resources\index.html
2020-04-11T08:12:02.1131329Z 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
2020-04-11T08:12:02.1131593Z 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
2020-04-11T08:12:02.1131836Z 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
2020-04-11T08:12:02.1132039Z 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
2020-04-11T08:12:02.1132255Z 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
2020-04-11T08:12:02.1132461Z 	at java.base/java.io.File.toPath(File.java:2292)
2020-04-11T08:12:02.1132669Z 	at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:178)
2020-04-11T08:12:02.1132881Z 	at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192)
2020-04-11T08:12:02.1133089Z 	at io.vertx.core.file.impl.FileResolver.unpackUrlResource(FileResolver.java:156)
2020-04-11T08:12:02.1133273Z 	at io.vertx.core.file.impl.FileResolver.resolveFile(FileResolver.java:139)
2020-04-11T08:12:02.1133487Z 	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:805)
2020-04-11T08:12:02.1133697Z 	at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:934)
2020-04-11T08:12:02.1133913Z 	at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:932)
2020-04-11T08:12:02.1134139Z 	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:975)
2020-04-11T08:12:02.1134357Z 	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:955)
2020-04-11T08:12:02.1134547Z 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
2020-04-11T08:12:02.1134754Z 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
2020-04-11T08:12:02.1134972Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-04-11T08:12:02.1135194Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-04-11T08:12:02.1135409Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-04-11T08:12:02.1135613Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vietj** [comment] 2020-04-14 16:30
is there a reproducer that can be executed in Vert.x on Windows ?

**Comment by cescoffier** [comment] 2020-04-14 16:42
Unfortunately no, only in Quarkus (RestEasy extension tests).

**Comment by vietj** [comment] 2020-04-14 16:58
do you think it would happen if we run the vertx test suite on windows ?

**Comment by vietj** [comment] 2020-04-14 16:58
is that the test `NotFoundExceptionMapperHttpRootTestCase#testHtmlResourceNotFound` that reproduces it ?

**Comment by cescoffier** [comment] 2020-04-14 17:01
I hope so!

It seems to be related to the file resolver - so should not be related to Quarkus. A simple vertx app using the file resolver should be able to reproduce it.

One detail, the stack trace I copied, the test was trying to load an non-existing file (and expect a file not found).

**Comment by vietj** [comment] 2020-04-14 17:03
yes it got a 500 error instead of a 404 that is likely triggered by the resolution failure

**Comment by vietj** [comment] 2020-04-15 09:56
is there a class loader in Quarkus that returns any file from the filesystem when asked a resource, i.e `classLoader.get("/Users/julien")` returns the `java.net.URL` with `file:/Users/julien` @cescoffier @stuartwdouglas ?

**Comment by stuartwdouglas** [comment] 2020-04-15 10:16
No, unless there is a major bug somewhere

**Comment by vietj** [comment] 2020-04-15 10:36
it seems in dev mode I get a path resolved this way (that's the only explanation I get):

the thread class loader is asked to resolve  `D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test16681797404956701656\src\main\resources\META-INF\resources` and it returns a file URL that returns a `file:/D:/a/quarkus/quarkus/extensions/resteasy/deployment/target/quarkus-dev-mode-test16681797404956701656/src/main/resources/META-INF/resources/` URL

**Comment by vietj** [comment] 2020-04-15 11:28
@cescoffier @stuartwdouglas

**Comment by cescoffier** [comment] 2020-04-15 12:13
Anything from Vert.x that changed around this? It is working using Vert.x 3.8.5

**Comment by vietj** [comment] 2020-04-15 13:47
There is no change in `FileResolver` in Vert.x since 3.8.5 that changes this.

The change maybe arises from the Vert.x Web `StaticHandler` or Vert.x Web in general.

Anyway, let me tell you what is happening inside the resolver:

1. the resolver is asked to resolve the file `D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test16681797404956701656\src\main\resources\META-INF\resources" and it returns a file URL file:/D:/a/quarkus/quarkus/extensions/resteasy/deployment/target/quarkus-dev-mode-test16681797404956701656/src/main/resources/META-INF/resources/not_found`
2. it creates a java `File` and check its existence that indicates it does not exist, so it will try to resolve it from current class loader
3. it check the existence of the parent dir that indeed exists because of the file `resources/index.html` and ask the class loader an URL for this resource (using `getResource(String)` method), the classloader returns an URL that is uses the _file_ protocol and resolves to this directory
4. vertx will try to unpack this directory and the resources is contains so it can look for `not_found`
5. when unpacking `index.html`, the file resolver will target to unpack it to the `new File(cachedDir, "D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test16681797404956701656\src\main\resources\META-INF\resources" and it returns a file URL file:/D:/a/quarkus/quarkus/extensions/resteasy/deployment/target/quarkus-dev-mode-test16681797404956701656/src/main/resources/META-INF/resources/")`
6. when getting the `java.nio.file.Path` to copy the resource, the file system will check that the path cannot be constructed because it contains the `:` char

I believe there are two issues here:

1/ in Vert.x we should check that unpacking file to cache always produce valid file name (so the cached file name should escape `:`. Currently it assumes that the URL returned by the class loader for a given name implies that this name is valid, e.g resolve `foo/bar.txt` returns an URL and therefore it is valid. In this case it asks to resolve `D:\...` and gets the same file and trust this name is valid
2/ somehow Quarkus seems to resolve `D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test16681797404956701656\src\main\resources\META-INF\resources" and it returns a file URL file:/D:/a/quarkus/quarkus/extensions/resteasy/deployment/target/quarkus-dev-mode-test16681797404956701656/src/main/resources/META-INF/resources/` to the same file URL and it seems odd to me but I don't know how Quarkus classloading works in dev mode, hence my question

We will fix the issue 1/ in Vert.x file resolver because it is a general issue and that will be in 3.9.1 .

If 2/ is true and it is not expected, then maybe you should have a look at it too.

**Comment by cescoffier** [comment] 2020-04-15 13:50
Thanks @vietj ! 

I will let @stuartwdouglas to comment on the last issue.
About the Vert.x issue, let me know when you have a fix, I will try to see if I can pass the CI test with it (not sure how yet, but I will try).

**Comment by vietj** [comment] 2020-04-15 13:51
I was able to run this case using a fork of Quarkus that is using the 3.9.1-SNAPSHOT with an hand deployed patched resolver https://github.com/vietj/quarkus/actions/runs/78710593

**Comment by cescoffier** [comment] 2020-04-15 13:52
Awesome!

**Comment by vietj** [comment] 2020-04-15 13:53
note if the point 2. is true and fixed, it might fix the issue as well because no unpack will happen since the classloader will return null

**Closed** 2020-04-15 17:23 UTC
Labels: bug
