### ISSUE TITLE
The values in some methods of JsonArray/JsonObject are not converted to json types.

### ISSUE THREAD

**Issue by okou19900722** [eclipse-vertx/vert.x#2972] opened 2019-05-30 11:33 UTC
some method like :
https://github.com/eclipse-vertx/vert.x/blob/d9bfe3ed9805706d4f3c1066e261c2ef004543ec/src/main/java/io/vertx/core/json/JsonArray.java#L524-L527

https://github.com/eclipse-vertx/vert.x/blob/d9bfe3ed9805706d4f3c1066e261c2ef004543ec/src/main/java/io/vertx/core/json/JsonArray.java#L663-L671

it conver the value to JsonArray if it's a List, conver to JsonObject if it's a map.

but some other method didn't conver.eg:forEach, stream,spliterator. So should we implements these methods

**Comment by danmana** [comment] 2020-02-25 16:44
Encountered a bug in 3.8.5 related to this (while migrating a codebase from vert.x 2 to 3).

basically a nested object: `{a: { b: ["lorem"] } }`) (created with new JsonObject/JsonArray and sent as a message reply)

Fails with `cannot cast ArrayList to JsonArray` if using `.getMap()`
```java
  // notice the .getMap()
  response.result().body().getJsonObject("a").getMap().forEach((key, val) -> {
    JsonArray b = (JsonArray) val;
  })
```

Does not fail if working directly with the JsonObject.forEach
```java
  // without .getMap()
  response.result().body().getJsonObject("a").forEach((entry) -> {
    JsonArray b = (JsonArray) entry.getValue();
  })
```

Could not reproduce this consistently, probably due to running in a cluster, but ocasionally the following was true:

```java
a.iterator().next().getValue().getClass() // JsonArray
.getMap().entrySet().iterator().next().getValue().getClass()) // ArrayList
```

Looks like it might be fixed in 4.0.0 by #3197

**Closed** 2021-08-02 15:18 UTC
