### ISSUE TITLE
Clustered Lock is not released if more locks are requested than available worker threads

### ISSUE THREAD

**Issue by naveen140990** [eclipse-vertx/vert.x#3126] opened 2019-10-04 06:33 UTC
I am facing this issue while migrating from vertx 3.5.4 to 3.7.x.

If I am requesting more locks than available workers, then lock is not released in vertx versions 3.6.x and 3.7.x. Please find the reproducer below:

https://github.com/naveen140990/ClusteredLockReproducer/blob/master/src/test/java/EventbusTest.java

Above same code works if I change vertx version to 3.5.4.
Also if I reduce numTestEvents in dataprovider(for above reproducer code) to a number less than 20 then also everything seems to be working.

**Comment by tsegismont** [comment] 2019-10-04 08:34
@naveen140990 could you please share a simplified reproducer? Thanks

**Comment by naveen140990** [comment] 2019-10-04 12:13
@tsegismont I have refactored code to simplify reproducer. numTestEvents variable holds value of concurrent locks requested.  When I use vertx version 3.5.4, locks are acquired correctly. But when version is upgraded to 3.7.0, only first lock is acquired and after 10 seconds(default timeout I guess), rest all other efforts return "io.vertx.core.VertxException: Timed out waiting to get lock" error message.

**Comment by naveen140990** [comment] 2019-10-07 09:05
@tsegismont This issue is present in recently released 3.8.2 version as well. Have you a got a chance to look into this? Thanks !

**Comment by tsegismont** [comment] 2019-10-07 13:26
@naveen140990 in Vert.x 3.5, locks were acquired on the internal worker pool and released on the worker pool. Your test passes with 3.5 but this implementation had other problems (like preventing internal tasks to execute).

We could create a dedicated pool to release locks (a cached thread pool with core pool size set to zero).

**Comment by naveen140990** [comment] 2019-12-19 11:43
Hi @tsegismont , I am thinking of  experimenting with vert.x 4 using milestone versions for a new project, but for that I would need this implementation. Could you please help me by giving an idea if this would indeed be available in general release? Thanks !

**Comment by tsegismont** [comment] 2019-12-19 15:25
Not sure what you mean. The implementation in master is present in
milestone4.

Le jeu. 19 déc. 2019 à 12:43, Naveen Katiyar <notifications@github.com> a
écrit :

**Comment by naveen140990** [comment] 2019-12-19 17:25
Probably I was not clear enough . Actually, I was asking about the fix of reported issue(Clustered Lock is not released if more locks are requested than available worker threads) . I have checked in milestone 4, but issue still exists. So, I wanted to enquire if this fix would be eventually provided in subsequent milestone versions ?

**Comment by tsegismont** [comment] 2019-12-20 08:32
My bad, I confused this issue with the other you commented on. Sorry.

No this one hasn't been fixed yet. It should be fixed in the next milestone.

**Comment by naveen140990** [comment] 2019-12-20 10:26
No Problem :)
I would be checking out future milestones for this fix. Thanks for the update !

**Comment by tsegismont** [comment] 2020-01-28 14:04
@vietj I added a test in Vert.x core and fixed HZ, Ignite and ZK cluster managers. ISPN does not need it because it has a non blocking API.

**Comment by tsegismont** [comment] 2020-01-29 10:28
Fixed by https://github.com/eclipse-vertx/vert.x/commit/86d5b6a7187386df7500c7f1e5823907ef4fc5a3 https://github.com/eclipse-vertx/vert.x/commit/ec8f7f94193e401dcdee75d0da15a66bab766bf2 https://github.com/vert-x3/vertx-hazelcast/commit/d3bf5286a0f291d6620130cf3a5fb68b9573ee77 https://github.com/vert-x3/vertx-hazelcast/commit/82c4a3f5be28c787079975edff03a4a057c5b297

**Closed by tsegismont** 2020-01-29 10:28 UTC
Labels: clustering
