### ISSUE TITLE
ClusteredEventBus publishes local subscription topics on the cluster

### ISSUE THREAD

**Issue by elventear** [eclipse-vertx/vert.x#3882] opened 2021-04-04 16:05 UTC
### Version

4.0.3

### Context

Migrating socket application from stand alone to cluster mode using Zookeper. I have noticed that all socket write IDs are being published to the cluster, which seemed suspicious and possible scalability problem for very busy network applications.

Further reviewing to the code showed that `NetSocket` registration should only expose it's write ID locally, which makes sense to me. https://github.com/eclipse-vertx/vert.x/blob/d7605ababc5d86334184c32ce2a123cfac6c3fdb/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java#L105

### Do you have a reproducer?

I have not created a reproducer, but I have been reviewing the code and comparing Vert.X 3.9.6 and 4.0.3. Comparing the two branches the behavior is not consistent and it seems to me there is a bug. 

When adding a new registration I see that the event bus, when clustered resolves to the following interactions in order.

On Vert.X 3.9.6:
1. Call `addRegistration` on `EventBusImpl.java`. https://github.com/eclipse-vertx/vert.x/blob/d2b24fd5bbb4c2672dab4af0f7b35275751fadcc/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java#L235
2. Call  overridden `addRegistration` in `ClusteredEventBus.java`. This call explicitly looks at the `localOnly` flag and does not register the address in the cluster if its local only. https://github.com/eclipse-vertx/vert.x/blob/d2b24fd5bbb4c2672dab4af0f7b35275751fadcc/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L186

On Vert.X 4.0.3:

1. Call `addRegistration`on `EventBusImpl.java`. https://github.com/eclipse-vertx/vert.x/blob/d7605ababc5d86334184c32ce2a123cfac6c3fdb/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java#L238
2. Call  overridden `onLocalRegistration` in `ClusteredEventBus.java`. This call does not take a `localOnly` flag and ends up registering the address in the cluster *always*. https://github.com/eclipse-vertx/vert.x/blob/d7605ababc5d86334184c32ce2a123cfac6c3fdb/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L128

### Steps to reproduce

1. Start application in clustered mode with Zookeper.
2. Create local consumer event handler with a subscription or open a `NetSocket`.
3. Inspect `/io.vertx/__vertx.subs` in Zookeper.
4. Local addresses or socket write IDs are published.

### Extra

Tested on macOS 11, openJDK 11.

**Comment by elventear** [comment] 2021-04-05 18:42
This sees to be an issue with the Zookeeper Cluster Manager that is not looking into `RegistrationInfo`.

**Comment by vietj** [comment] 2021-04-06 06:37
can you reproduce this with another cluster manager like Hazelcast or Infinispan @elventear ?

**Comment by tsegismont** [comment] 2021-04-06 08:29
Closing as duplicate of https://github.com/eclipse-vertx/vert.x/pull/3843

See user group thread https://groups.google.com/g/vertx/c/e2g6qHauW1M/m/ZinSXg-XBAAJ

This should be filed on the `vertx-zookeeper` repository.

**Closed** 2021-04-06 08:40 UTC
Labels: duplicate

**Comment by elventear** [comment] 2021-04-06 15:17
@tsegismont I checked briefly the Hazelcast implementation. I see that the `SubsMapHelper` keeps track of local and non-local registrations separately. Will it also not publish the local addresses to the cluster? (I did not have time to figure out that).

**Comment by tsegismont** [comment] 2021-04-06 16:28
@elventear yes, it does not publish local addresses to the cluster

**Comment by elventear** [comment] 2021-04-06 16:32
@tsegismont I will create a bug in eclipse-vert.x/vertx-zookeper. And I can help fix the ZooKeeper implementation.

**Comment by tsegismont** [comment] 2021-04-06 18:59
@elventear awesome!

**Comment by elventear** [comment] 2021-04-07 05:13
Created vert-x3/vertx-zookeeper#117
