### ISSUE TITLE
Empty Host Header still not supported

### ISSUE THREAD

**Issue by querdenker2k** [eclipse-vertx/vert.x#5011] opened 2023-12-06 08:07 UTC
### Version

4.4.6

### Context

Empty host header not supported still in 4.4.6, but should be already fixed.
see https://github.com/eclipse-vertx/vert.x/issues/4879

### Reproducer

curl -iv -H "User-Agent:" -H "Accept:" -H "Host:" http://localhost:8080
Fails with 500 and an NullPointerException in log.

**Comment by vietj** [comment] 2023-12-06 08:35
this has been fixed in 4.4.6 for HTTP server, I think you are instead experiencing an NPE with another component, maybe vertx web. Can you print the stack trace here to show your NPE or provide a reproduder project ?

**Closed** 2023-12-06 08:51 UTC
Labels: bug

**Comment by querdenker2k** [comment] 2023-12-06 09:07
I am using this to start
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.vertx:vertx-web:4.4.6

import io.vertx.core.Vertx;
import io.vertx.ext.web.Router;
import static java.lang.System.*;

public class VertxHostNpe {

    public static void main(String... args) throws Exception {
    
            Vertx vertx = Vertx.vertx();
            Router router = Router.router(vertx);
            router.get("/").handler(ctx -> {
                ctx.response().end("Hello World! " + ctx.request().host());
            });


            vertx.createHttpServer()
                .requestHandler(router)
                .listen(8080);

            Thread.sleep(100000);    

    }
}
```
and run this curl
`curl -iv -H "User-Agent:" -H "Host:" http://localhost:8080`

This is the exception in vertx
```
Dez. 06, 2023 10:06:22 AM io.vertx.ext.web.RoutingContext
SCHWERWIEGEND: Unhandled exception in router
java.lang.NullPointerException
	at io.vertx.core.net.impl.HostAndPortImpl.<init>(HostAndPortImpl.java:141)
	at io.vertx.core.net.HostAndPort.create(HostAndPort.java:20)
	at io.vertx.ext.web.impl.ForwardedParser.calculate(ForwardedParser.java:137)
	at io.vertx.ext.web.impl.ForwardedParser.host(ForwardedParser.java:76)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.host(HttpServerRequestWrapper.java:183)
	at VertxHostNpe.lambda$main$0(VertxHostNpe.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpRequestChannelRead(WebSocketServerExtensionHandler.java:160)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by vietj** [comment] 2023-12-06 09:10
yeah that is an issue in vertx-web

**Comment by vietj** [comment] 2023-12-06 09:10
I think it has been fixed but not in 4.4.6

**Comment by querdenker2k** [comment] 2023-12-06 09:12
I tested with 4.5.0 as well, but there is the same error.

**Comment by vietj** [comment] 2023-12-06 09:16
yeah I figured out, I'll be providing a fix for that and create an issue in vertx-web @querdenker2k thank you

**Comment by vietj** [comment] 2023-12-06 09:22
Actually it seems your case is different, empty host header seems to be handled correctly.

I don't see the host header in your reproducer in wireshark, so it is the absence of host header that fails.

**Comment by vietj** [comment] 2023-12-06 09:23
<img width="897" alt="Screenshot 2023-12-06 at 10 23 12" src="https://github.com/eclipse-vertx/vert.x/assets/225674/bf337194-626a-49e1-907f-3135eb9ec5f9">

**Comment by vietj** [comment] 2023-12-06 09:39
https://github.com/vert-x3/vertx-web/pull/2536
