### ISSUE TITLE
Connection pool can create connections which ignore keep alive settings

### ISSUE THREAD

**Issue by kotcrab** [eclipse-vertx/vert.x#3687] opened 2020-12-08 19:07 UTC
### Version

3.9.1 but this also happens on latest commit

### Context

Since some time we've seen `WebClient` throwing `Connection reset` error on first request after a period of inactivity. I know that our gateway closes inactive connections after some time. The question was why `WebClient` doesn't close such connections, the default keep alive settings should remove inactive connections after 60 seconds. After some debugging I tracked the issue down to `Pool` having connections that don't have `expirationTimestamp` set. I believe there's some race condition with how connections are created and consumed. The flow is like this:

1. First request is started. First connection will be created but it takes significant time for it to be connected.
2. In the same time a second request is started. A second connection will be created but this one connects instantly.
3. Second request finishes.
4. Second connection is now available and it's used to complete the first request.
5. First connection has finished connecting but the waiter list is empty. It will sit unused in the pool. `expirationTimestamp` is not set so keep alive settings are ignored.
6. After some time our gateway closes the inactive connection by sending RST packet.
7. Third request is started, it will use that first connection (now closed on the gateway side) and throw `Connection reset` error.

### Do you have a reproducer?

See [here](https://github.com/kotcrab/vert.x/commit/53fb81b28d49fb7b5e0959e94d5300176f04c829).
Note that I added a delay in `HttpChannelConnector` to simulate slow first connection. This reproduces the issue reliably. Of course in our environment I can reproduce the issue with unchanged vertx 3.9.1 and 3.9.4.

### Steps to reproduce

1. Run `IssueReproducer.java`
2. Output should look like this
```
Connection satisfied waiters: 1
Request response: 200
Request response: 200
Connection with expiration
Connection with expiration
Connection with expiration
Connection with expiration
Connection satisfied waiters: 0
Connection with expiration
Connection with no expiration
Connection with expiration
Connection with no expiration
Connection with no expiration
...
```
3. A pool now has a connection that won't be removed even if its keep alive time passes (`expirationTimestamp` of this connection is 0).

### Extra

Tested on Linux and macOS. JVM 11.

**Comment by vietj** [comment] 2020-12-09 15:59
the code you shown seems to be for Vert.x 4

**Comment by kotcrab** [comment] 2020-12-09 16:05
> 3.9.1 but this also happens on latest commit

Yep I made the test case with latest commit on master. If you want I can port it to 3.9 but it's not that different...

**Comment by vietj** [comment] 2020-12-09 16:07
yes it would be better, because I am not sure the issue happens in 4.0

I don't get the same results than you when trying your reproducer;

**Comment by vietj** [comment] 2020-12-09 16:09
so the issue could be solved in various ways I think

- one is that `expirationTimestamp` could be initialized early and not only when the connection is recycled
- another way could be that when a connection is created, the waiter is removed from the list which changes how the pool progress

**Comment by vietj** [comment] 2020-12-09 16:12
both could be done too

I think one thing we need to keep in mind when fixing this, is to have the future support of waiter expiration too.

**Comment by kotcrab** [comment] 2020-12-09 16:28
[Test on 3.9 branch](https://github.com/kotcrab/vert.x/commit/9b3d0be25bf4d07919bb5690ddf544b6ae90ce02)

> I don't get the same results than you when trying your reproducer;

Hmm strange. With the added delay in `HttpChannelConnector` it works for me every time.

**Comment by vietj** [comment] 2020-12-10 08:30
I'll have a try on 3.9.

**Comment by vietj** [comment] 2020-12-10 08:41
@kotcrab can you try this change 

```java
  public boolean isValid() {
    long expirationTimestamp = keepAliveTimeout == 0 ? 0L : System.currentTimeMillis() + keepAliveTimeout * 1000;
    if (expirationTimestamp == 0) {
      System.out.println("Connection with no expiration");
    } else {
      System.out.println("Connection with expiration");
    }
    return expirationTimestamp == 0 || System.currentTimeMillis() <= expirationTimestamp;
  }
```

**Comment by vietj** [comment] 2020-12-10 08:51
I believe it's hard to reproduce with a real case because it means we would need have TCP handshake hang which is not really possible

**Comment by vietj** [comment] 2020-12-10 09:38
actually this fix is incorrect, we should really compute this initially.

**Comment by vietj** [comment] 2020-12-10 09:38
although it solves the issue in this case

**Closed** 2020-12-10 10:00 UTC
Labels: bug

**Comment by kotcrab** [comment] 2020-12-10 17:38
Thanks, I can confirm that the fix works for my reproducer.

> I believe it's hard to reproduce with a real case because it means we would need have TCP handshake hang which is not really possible

Yeah. It's hard to say what is exactly going on in our env that causes this but it was pretty frequent.
