### ISSUE TITLE
Vertx web client sends server cookies back in multiple COOKIE headers and not anymore in a single semicolon separated field.

### ISSUE THREAD

**Issue by VMalko** [eclipse-vertx/vert.x#3448] opened 2020-06-15 17:02 UTC
Hello, 

### Version

vertx-core: 3.8.5
vertx-web: 3.8.5
vertx-web-client: 3.8.5

### Context

Vertx web client sends server cookies back in multiple COOKIE headers and not anymore in a single semicolon separated field.

As a result server handle only one cookie. It cause authentication/session issue.

### Do you have a reproducer?

https://github.com/VMalko/vertx-cookie-test.git

There is cookieTest which fails as server handle only one cookie ("testName", "testValue")

### Steps to reproduce

1. clone test project
2. execute cookieTest. Check that web client sends to server http endpoint "/cookieCheck" cookies back in multiple COOKIE headers and not anymore in a single semicolon separated field.
As a result server handle only one cookie ("testName", "testValue").

It is implemented with Vertx server. But external production server do the same - handle only one cookie. 

### Extra

HTTP protocol version 1.1

**Comment by vietj** [comment] 2020-07-02 15:46
can you tell with which version you observe a single cookie was sent ?

**Comment by VMalko** [comment] 2020-07-03 08:32
Hello vietj,

HTTP version 1.1

**Comment by vietj** [comment] 2020-07-03 08:35
I meant which version of Vert.x

**Comment by VMalko** [comment] 2020-07-03 08:43
Version
vertx-core: 3.8.5
vertx-web: 3.8.5
vertx-web-client: 3.8.5

**Comment by vietj** [comment] 2020-07-03 09:27
I meant actually with which version of Vert.x (so not 3.8.5) did you observe the test you wrote passing ?

**Comment by VMalko** [comment] 2020-07-03 14:01
I tested only on Vert.x 3.8.5 version. So, there is no passed test.

**Comment by tsegismont** [comment] 2021-02-22 13:14
This was fixed in 8c4829629ac6a12d7f69d0db96b783bb09df2559. I will backport the fix to 3.9 branch.

**Comment by tsegismont** [comment] 2021-02-22 13:21
Actually the fix was originally applied to 3.9 branch (https://github.com/vert-x3/vertx-web/pull/1790)

Closing as duplicate of https://github.com/vert-x3/vertx-web/issues/1716

**Closed by tsegismont** 2021-02-22 13:21 UTC
Labels: bug
