### ISSUE TITLE
Hostname resolution does not handle answers set in additional section instead of answers section

### ISSUE THREAD

**Issue by wooque** [eclipse-vertx/vert.x#3150] opened 2019-10-17 10:28 UTC
I'm trying to create websocket client, but DNS resolution fails. 
It doesn't fails consistently, sometimes it succeeds.
Example
```java
package test;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.http.HttpClientOptions;

public class Test extends AbstractVerticle {
  @Override
  public void start() {
    var httpOpts = new HttpClientOptions().setSsl(true);
    var client = vertx.createHttpClient(httpOpts);

    client.webSocket(443, "echo.websocket.org", "/", res -> {
      if (res.failed()) {
        res.cause().printStackTrace();
        return;
      }
      System.out.println("SUCCESS");
      res.result().handler(System.out::println);
    });
  }
}
```
Exception
```
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'echo.websocket.org' failed to resolve 'echo.websocket.org.Home' after 3 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:543)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:64)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:400)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:204)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:196)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Dig output
```
; <<>> DiG 9.14.7 <<>> echo.websocket.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26605
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;echo.websocket.org.		IN	A

;; ANSWER SECTION:
echo.websocket.org.	60	IN	A	174.129.224.73

;; Query time: 45 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Oct 17 12:26:26 CEST 2019
;; MSG SIZE  rcvd: 52
```

I'm using vertx 3.8.2 on OpenJDK 11 on Arch Linux.

**Comment by wooque** [comment] 2019-10-17 10:40
Workaround that works for now is to disable Vert.x DNS resolution with 
`-Dvertx.disableDnsResolver=true`

**Comment by vietj** [comment] 2019-10-17 10:48
can you give a full reproducer ? we don't see the VertxOptions in your example

**Comment by vietj** [comment] 2019-10-17 10:49
what is your OS ?

**Comment by wooque** [comment] 2019-10-17 11:57
>can you give a full reproducer ? we don't see the VertxOptions in your example

It's simple project created from Vert.x starer, I've extracted the basics into this repo: https://github.com/wooque/vertx_issue. 
I'm running it with `./gradew run`

>what is your OS ?

Arch Linux

**Comment by vietj** [comment] 2019-10-17 12:59
do you have search domain configured in your `/etc/resolv.conf` ?

**Comment by wooque** [comment] 2019-10-17 13:10
Here is the whole content of `/etc/resolv.conf`
```
# Generated by NetworkManager
search Home
nameserver 192.168.1.1
```

**Comment by vietj** [comment] 2019-10-17 13:20
can you enable Netty logging to have the Netty resolver log what is going ?

**Comment by wooque** [comment] 2019-10-17 13:25
How do I do that? Could you point me to docs for that?

**Comment by vietj** [comment] 2019-10-17 14:43
you can have a look here https://vertx.io/docs/vertx-core/java/#netty-logging

you can enable the category `io.netty.resolver` to have only logging for the resolver.

**Comment by wooque** [comment] 2019-10-17 17:42
when it succeeds these are logs
```
Oct 17, 2019 7:39:30 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider <clinit>
FINE: Default DNS servers: [/192.168.1.1:53] (sun.net.dns.ResolverConfiguration)
Oct 17, 2019 7:39:31 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle
Oct 17, 2019 7:39:31 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0xd50b8ad9] WRITE: UDP, [31848: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org. IN A)
Oct 17, 2019 7:39:31 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0xd50b8ad9] WRITE: UDP, [34044: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org. IN AAAA)
Oct 17, 2019 7:39:31 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0xd50b8ad9] RECEIVED: UDP [34044: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:37100, 34044, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(echo.websocket.org. IN AAAA)
	DefaultDnsRawRecord(websocket.org. 60 IN SOA 69B)
Oct 17, 2019 7:39:31 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0xd50b8ad9] RECEIVED: UDP [31848: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:37100, 31848, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(echo.websocket.org. IN A)
	DefaultDnsRawRecord(echo.websocket.org. 60 IN A 4B)
SUCCESS
```
And on the error
```
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider <clinit>
FINE: Default DNS servers: [/192.168.1.1:53] (sun.net.dns.ResolverConfiguration)
Oct 17, 2019 7:38:33 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [56566: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org. IN A)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [44760: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org. IN AAAA)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [56566: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 56566, QUERY(0), NoError(0))
	DefaultDnsQuestion(echo.websocket.org. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
	DefaultDnsRawRecord(echo.websocket.org. 23 IN A 4B)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [44760: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 44760, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(echo.websocket.org. IN AAAA)
	DefaultDnsRawRecord(websocket.org. 60 IN SOA 69B)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [29109: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org. IN CNAME)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [29109: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 29109, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(echo.websocket.org. IN CNAME)
	DefaultDnsRawRecord(websocket.org. 60 IN SOA 69B)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [14635: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org.Home. IN A)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [354: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org.Home. IN AAAA)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [354: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 354, QUERY(0), NXDomain(3), RD RA)
	DefaultDnsQuestion(echo.websocket.org.Home. IN AAAA)
	DefaultDnsRawRecord(. 39 IN SOA 64B)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [14635: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 14635, QUERY(0), NXDomain(3), RD RA)
	DefaultDnsQuestion(echo.websocket.org.Home. IN A)
	DefaultDnsRawRecord(. 39 IN SOA 64B)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsQueryContext query
FINE: [id: 0x538ef055] WRITE: UDP, [12466: /192.168.1.1:53], DefaultDnsQuestion(echo.websocket.org.Home. IN CNAME)
Oct 17, 2019 7:38:33 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
FINE: [id: 0x538ef055] RECEIVED: UDP [12466: /192.168.1.1:53], DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:43495, 12466, QUERY(0), NXDomain(3), RD RA)
	DefaultDnsQuestion(echo.websocket.org.Home. IN CNAME)
	DefaultDnsRawRecord(. 39 IN SOA 64B)
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'echo.websocket.org' failed to resolve 'echo.websocket.org.Home' after 3 queries 
```

**Comment by vietj** [comment] 2019-10-17 18:22
so it does not always fail ?

**Comment by wooque** [comment] 2019-10-17 18:34
Yes, I'd say it's 50/50

**Comment by wooque** [comment] 2019-10-17 18:57
It's network specific, I tried example while connected to mobile hotspot and it worked everytime, but when I switch to fiber internet I usually using it fails half the time.
`dig` on the other hand never fails.

I noticed when it fails there is always this line in log, never when it succeeds:
`DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)`

**Comment by hppranaav** [comment] 2019-11-25 09:41
> Workaround that works for now is to disable Vert.x DNS resolution with
> `-Dvertx.disableDnsResolver=true`

Hi @wooque  I am running a simple example program through IntelliJ IDE and am hitting the same roadblock. Would like to know how I can enable the above flag on the IDE
Also where how exactly do you compile on CLI with the flag?

**Comment by wooque** [comment] 2019-11-25 09:49
You add it `-Dvertx.disableDnsResolver=true` to **Program arguments**.
In CLI it depends what build system you are using, you need to consult documentation, I'm using Gradle, and you add it to **args** in **run** block.

**Comment by hppranaav** [comment] 2019-11-25 13:35
@wooque thanks! But I am still seeing the same error even after updating the flag through the program arguments

**Comment by wooque** [comment] 2019-11-25 13:39
I don't know how are you running it in IDE, I run it through vertx Launcher class, so I set `io.vertx.core.Launcher` as main class and in program arguments 
`run com.example.SomeClass -Dvertx.disableDnsResolver=true`

**Comment by hppranaav** [comment] 2019-11-29 11:18
I'm doing it the same way but the error stil persists

**Comment by cpdyj** [comment] 2020-01-07 08:59
Last time I found Vert.x resolution can't work correctly with mutiple adapter on Windows. (such as enable Hyper-V)

**Comment by vinesh178** [comment] 2020-01-22 02:37
Put the value -Dvertx.disableDnsResolver=true in VM options

**Comment by brunoaduarte** [comment] 2020-02-08 05:09
`-Dvertx.disableDnsResolver=true` doesn't fix the problem, only changes the error message to this one
```
java.net.UnknownHostException: No such host is known (https://www.google.com)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:202)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:164)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:141)
	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:140)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:93)
	at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:166)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:100)
	at io.vertx.core.http.impl.pool.Pool$Holder.connect(Pool.java:126)
	at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:256)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by vietj** [comment] 2020-02-08 14:38
@brunoaduarte can you show your code ?

**Comment by brunoaduarte** [comment] 2020-02-08 17:13
Nevermind @vietj , i tried again today and it worked.
Maybe my provider was having DNS issues yesterday, i don't know 🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️
Anyway here's the code
```
@ExtendWith(VertxExtension.class)
public class TestMainVerticle {

	@Test
	void checkAddressGet(Vertx vertx, VertxTestContext testContext) {
		WebClient webClient = WebClient.create(vertx);
		webClient.get(80, "www.google.com", "/").as(BodyCodec.string())
				.send(testContext.succeeding(resp -> {
					testContext.verify(() -> {
						assertEquals(200, resp.statusCode());
						System.out.println(resp.body());
						testContext.completeNow();
					});
				}));

	}

}
```

**Comment by vietj** [comment] 2020-02-09 07:25
I'm asking because the error message was printing it could not resolve `https://www.google.com` which makes me think you use something like `webClient.get("http://www.google.com")` instead

**Comment by brunoaduarte** [comment] 2020-02-10 20:32
> I'm asking because the error message was printing it could not resolve `https://www.google.com` which makes me think you use something like `webClient.get("http://www.google.com")` instead

You're right, on that attempt my code was like `webClient.get(80, "https://www.google.com", "/")`
But only because `webClient.get(80, "www.google.com", "/")` wasn't working neither... i'm sure i tried both and none of them worked.
Anyway, problem is fixed now. Thanks!

**Comment by vietj** [comment] 2020-03-18 15:24
@wooque it seems indeed that the presence of the OPT record in the DNS response causes the issue. There is this issue logged in Netty that seems similar and has been reported : https://github.com/netty/netty/issues/9632

I will not close this issue for now as it seems unclear whether it still applies. To understand more clearly what happens it would be good to have a TCP capture of the traffic between Vert.x (or Netty) and the server to have the full exchange to investigate what is happening.

**Comment by vietj** [comment] 2020-03-18 15:24
@wooque if you can still reproduce the issue, could you capture the exchange in a pcap file and share it ?

**Comment by wooque** [comment] 2020-03-18 17:28
@vietj Yes I can, here is the pcap file (set .txt extension so github would let me upload, just rename it to .pcap)
[dump.txt](https://github.com/eclipse-vertx/vert.x/files/4350398/dump.txt)

**Comment by vietj** [comment] 2020-03-18 17:43
thanks @wooque can you give more details about your test, i.e which server you reached and which is your DNS resolver set for the test ?

**Comment by wooque** [comment] 2020-03-18 21:24
@vietj I posted earlier test case I used to reproduce issue: https://github.com/wooque/vertx_issue
it tries to resolve echo.websocket.org, and dns resover is my ISP's

**Comment by vietj** [comment] 2020-03-19 10:01
thanks @wooque I'll investigate this issue today

**Comment by vietj** [comment] 2020-03-19 10:03
@wooque can you try the same but setting `optResourceEnabled` to false in `AddressResolverOptions` when creating a Vertx instance

**Comment by vietj** [comment] 2020-03-19 10:26
it seems that the DNS server you are using sometimes sends an incorrect response, it will send the actual response in the DNS _Answers_ packet, here is a comparison of a correct DNS response (that I captured myself using a correct resolver)

##  Correct DNS response

<img width="702" alt="Screen Shot 2020-03-19 at 11 21 50" src="https://user-images.githubusercontent.com/225674/77057365-20a6b180-69d4-11ea-89d3-0d39a1501f54.png">

## DNS response with Additional Records / Answers swapped

<img width="674" alt="Screen Shot 2020-03-19 at 11 22 23" src="https://user-images.githubusercontent.com/225674/77057384-2603fc00-69d4-11ea-9b5b-fe800ad37a8c.png">

Perhaps that other resolvers are tolerant to this kind of incorrect responses and the resolver we are using should do the same, that's an open question.

**Comment by vietj** [comment] 2020-03-19 11:01
the JVM uses `getaddreinfo` - I haven't investigated what it does in practice

**Comment by vietj** [comment] 2020-03-19 11:01
@wooque are you able to determine if using JVM and obtaining an incorrect answer, the resolution still happens ?

**Comment by vietj** [comment] 2020-03-19 11:06
I found that JDK does not uses OPT resource enabled by default, so the issue shall not happen on your system. I think that if you disable OPT in Vert.x then it shall work correctly on your system. Can you have a try and report @wooque ?

I believe in 3.9.0 we should change this setting to have OPT resource disabled by default and I'm waiting for your feedback.

**Comment by wooque** [comment] 2020-03-19 18:20
Yep, I tried setting `optResourceEnabled` to false in `AddressResolverOptions` when creating a Vertx instance as you suggested and this problem does not manifest anymore.

**Comment by vietj** [comment] 2020-03-20 07:13
I will close this issue (as a non issue) since the DNS resolver is faulty and it is not a Vert.x issue.

**Closed by vietj** 2020-03-20 07:13 UTC
