### ISSUE TITLE
local address  are registered to the cluster

### ISSUE THREAD

**Issue by jitawangzi** [eclipse-vertx/vert.x#4000] opened 2021-07-06 10:09 UTC
### Questions

I use websocket through vertx and enable the cluster (zookeeper). I noticed that when a websocket connection is created, an address will be generated and registered to the zookeeper. When the registration is cancelled, only the data in the address will be cleared, not clear the address, causing the zookeeper node to increase indefinitely,Many nodes like this: 

__vertx.net.fe071115-964d-40d8-b908-3e764188d2ad
__vertx.ws.014f5f57-829e-45a8-9580-bc42007cb33b

### Version

4.1.1

### Context

i read the source code,found this : 

```java
class  NetSocketImpl

  void registerEventBusHandler() {
    Handler<Message<Buffer>> writeHandler = msg -> write(msg.body());
    registration = vertx.eventBus().<Buffer>localConsumer(writeHandlerID).handler(writeHandler);
  }
```

and

```java
class  WebSocketImplBase

  void registerHandler(EventBus eventBus) {
    Handler<Message<Buffer>> binaryHandler = msg -> writeBinaryFrameInternal(msg.body());
    Handler<Message<String>> textHandler = msg -> writeTextFrameInternal(msg.body());
    binaryHandlerRegistration = eventBus.<Buffer>localConsumer(binaryHandlerID).handler(binaryHandler);
    textHandlerRegistration = eventBus.<String>localConsumer(textHandlerID).handler(textHandler);
  }
```

used  method   `<T> MessageConsumer<T> localConsumer(String address)`  when registering  ,

then will arrive this : 

class ClusteredEventBus , method :  

```java
  @Override
  protected <T> void onLocalRegistration(HandlerHolder<T> handlerHolder, Promise<Void> promise) {
    if (!handlerHolder.isReplyHandler()) {
      RegistrationInfo registrationInfo = new RegistrationInfo(
        nodeId,
        handlerHolder.getSeq(),
        handlerHolder.isLocalOnly()
      );
      clusterManager.addRegistration(handlerHolder.getHandler().address, registrationInfo, Objects.requireNonNull(promise));
    } else if (promise != null) {
      promise.complete();
    }
  }
```

the handlerHolder，`isReplyHandler()` is false，but `localOnly` is  true，
so the address  is registered to the clusterManager。

I think this address should not be registered to the clusterManager,because  the address is registered with localConsumer method,

Maybe it should be so?

`if (!handlerHolder.isReplyHandler() && !handlerHolder.isLocalOnly())`

**Comment by vietj** [comment] 2021-07-07 07:14
can you provide a reproducer project ?

**Comment by vietj** [comment] 2021-07-07 07:47
I cannot comment about whether this is correct or not from the perspective of the clustered event bus and we should wait until @tsegismont is back from PTO. However when the WebSocket is closed the message consumer should be removed from the event-bus, can you check whether it happens on your side?

**Comment by vietj** [comment] 2021-07-07 07:54
you can look at the `WebSocketImplBase#handleClose` method that unregisters such consumers

**Comment by jitawangzi** [comment] 2021-07-07 08:41
I don’t know how to provide a reproducer project, because the zookeeper environment is needed and it needs to be connected to the zookeeper to see the uncleaned data.


To be sure, when the WebSocket is closed, the related message consumers have been removed from the event bus, this is no problem, and the message consumer  are also removed  in the cluster manager, but the message left itself。

For example, a WebSocket consumer Saved in zookeeper like this:
io.vertx/__vertx.subs/**__vertx.ws.04ac3936-d566-4edb-96a8-8cc6921d470c**/*f013494a-87cd-4af0-8765-ba8223ad6e27-109*


**__vertx.ws.04ac3936-d566-4edb-96a8-8cc6921d470c** is a websocket connection (message or address), *f013494a-87cd-4af0-8765-ba8223ad6e27-109* is one of the consumer,
When websocket is closed, *f013494a-87cd-4af0-8765-ba8223ad6e27-109* consumer will be cleaned up, but **__vertx.ws.04ac3936-d566-4edb-96a8-8cc6921d470c** is reserved.

With more and more websocket connections, there will be more and more empty nodes like this, resulting in unlimited growth of __vertx.subs node.

I think this may not be a problem with vertx-zookeeper. If this message is not registered to the cluster manager, there will be no problem.

**Comment by vietj** [comment] 2021-07-07 10:01
normally the message consumer should be unregistered when the WebSocket is
closed

**Comment by mmoses** [comment] 2021-12-20 08:03
Hey i have notice a new behavior that is think is connected - on the 4.2.2 version, the local message are being serialized and back to object when send on the same JVM, in the 3.9.11 the object was passed (without serialization) to the local consumer this behavior effects dramatically on the performance.

**Comment by tsegismont** [comment] 2022-04-28 15:45
@jitawangzi this issue seems specific to the Zookeeper implementation. We have a test that verifies socket handlers are removed on close: https://github.com/eclipse-vertx/vert.x/blob/14551ebf842ca74cd423665402a0d80347b917e1/src/test/java/io/vertx/core/net/NetTest.java#L3602-L3619

I am moving this issue to the `vertx-zookeeper` repo

**Comment by tsegismont** [comment] 2022-04-28 15:50
Moved to https://github.com/vert-x3/vertx-zookeeper/issues/128

**Closed by tsegismont** 2022-04-28 15:50 UTC
Labels: invalid

**Comment by tsegismont** [comment] 2022-04-28 15:53
@mmoses hi, I don't believe this is related. Actually, I'm not sure what the problem is. Indeed, in Vert.x 4 local consumers are registered to the eventbus (we had to do this in order to unify consumer lookup). Yet if a local consumer is selected as destination for a message, the serialization is by-passed (internally we use the same method as for local delivery).
