### ISSUE TITLE
4.34 can't get the MySQLClient.LAST_INSERTED_ID

### ISSUE THREAD

**Issue by richard20200101** [eclipse-vertx/vert.x#4515] opened 2022-10-22 05:55 UTC
### Questions
<img width="801" alt="image" src="https://user-images.githubusercontent.com/61450147/197322877-0369aa7f-c2b6-4b2c-84df-906f30ef81de.png">

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version
4.3.4
Which version(s) did you encounter this bug ?
"rows.property(MySQLClient.LAST_INSERTED_ID);" retuen null , so i have go back 4.1.4
### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by tsegismont** [comment] 2022-10-24 12:18
This is probably because the query actually did not return a generated id.

Before Vert.x 4.3.4, the MySQL Client would always returns a `Long` with value set to `0`. But now it just returns `null` if no id was generated.

To emulate the previous behavior, you should do: 

```java
resultHandler.handle(Future.succeededFuture(lastInsertId == null ? 0L : lastInsertId));
```

**Comment by tsegismont** [comment] 2022-10-24 12:19
Closing as not a bug. If you have further questions, please report to the correct repository (`vertx-sql-client`).

**Closed by tsegismont** 2022-10-24 12:19 UTC
Labels: question
