### ISSUE TITLE
HTTP/2 requests pending after connection crash

### ISSUE THREAD

**Issue by elR1co** [eclipse-vertx/vert.x#3400] opened 2020-05-06 08:40 UTC
### Version

3.9.0

### Context

In a microservices application, we are doing an HTTP call from Gateway to specific service which is streaming a file directly back to HTTP response. When a user crashes its connection while streaming, a Vertx exception (io.vertx.core.VertxException: Connection was closed) is not caught immediately. We can see this error in logs only after the WebClient idle timeout ends. By the time, if WebClient is configured with HTTP/2, the next HTTP requests are pending. If WebClient is configured by default with HTTP1, it is fine, the next requests are ending.

Full description is [here](https://groups.google.com/forum/#!topic/vertx/Dy9nQvlhKFA).

### Do you have a reproducer?

Yes.

https://github.com/elR1co/http2-reproducer

### Steps to reproduce

See https://github.com/elR1co/http2-reproducer/blob/master/README.md

### Extra

* JDK11, MacOS X

**Comment by vietj** [comment] 2020-05-06 16:45
@elR1co the issue is caused due to the gateway server connection close failing before the http client response is received. At this spot, the server response error is not reported to the pipe body codec that will stream the client response to the (closed) server response. This leads to the HTTP/2 client response not sending back window changes to the server that will not be able to emit data. The issue is fixed in https://github.com/vert-x3/vertx-web/issues/1600

**Closed** 2020-05-06 16:45 UTC
Labels: invalid
