### ISSUE TITLE
Improve handling of exceptions thrown in Future handlers

### ISSUE THREAD

**Issue by willisblackburn** [eclipse-vertx/vert.x#1568] opened 2016-08-07 16:38 UTC
In my multi-developer Vert.x 3.x project it seems very easy to write code that doesn't handle exceptions well. I think that Vert.x could do better here.

I've attached an example of one of the common scenarios. The program invokes some method that returns a Future. This is often a method that accesses a database or other web service. In the example I call someAsyncMethod, which just sets a timer. The handler for the database or web service responses (the timer handler here) does some stuff and then completes the Future it returned earlier. However, due to a programming error or unexpected condition, the handler throws an exception.

In someAsyncMethod, I've anticipated that the timer handler may throw, so I catch any exception and fail the Future. If I don't do this, then any exception will propagate back to Vert.x, and the Future I returned from someAsyncMethod will never be completed. But the exception thrown from the caller's handler wounds up being caught by the catch block in the timer handler. It then tries to fail the Future. Since the Future is already completed, the call to fail throws IllegalStateException. That exception then masks the original exception. In production we see IllegalStateException in the log but have no idea what actually triggered it.

I've shown one possible solution in someOtherAsyncMethod. Here I move the call to complete outside the try block so that any exceptions thrown by the handler will propagate out of this handler. This at least produces the right message in the log. It's not easy to do consistently, though.

Another strategy would be to check whether or not the Future is already completed in the catch block, and do "something else" if it's already completed. But the "something else" would probably be just writing the exception to the log, so there's some record of what went wrong, or rethrowing it (this is what Future.compose does), which will ultimately return it to the Vert.x event loop. There's nothing else the handler can do because the future has already completed.

Some recommendations for how Vert.x could handle this situation better:
- Don't allow exceptions to propagate from a handler to the method that completed the Future. The completing method can't possibly handle a random exception from the handler in any meaningful way. If a handler throws, Vert.x should treat that as an unrecoverable condition and just log it. Perhaps there could be option to install a global exception handler that would do something else.
- Do something with the exception passed to Future.fail, even if the future is already completed. Either include it in the IllegalStateException that fail will throw, or just rethrow it directly, which seems to be the behavior recommend by Future.compose.

[FutureFail.zip](https://github.com/eclipse/vert.x/files/405592/FutureFail.zip)

**Comment by vietj** [comment] 2016-08-22 09:53
- Vertx provides since 3.3 `Vertx#exceptionHandler` and `Context#exceptionHandler` that allow to catch `Throwable` thrown during tasks execution on a `Context`
- I agree that `complete()` or `fail(err)` should not throw an exception and rather return a boolean that says wether or not the future was _completed_ - or perhaps we should have safe version that does that `failIfNotCompleted` / `completeIfNotCompleted`, although I don't think that not throwing anymore an exception would break something in user code.

**Comment by akshaykumar3** [comment] 2017-01-02 11:31
But doesn't Context changes in Future?
So we might have to add Context#exceptionHandler in every Future.
Can we avoid that and have a central place of catching any exception?

**Comment by austin-beer** [comment] 2020-08-15 14:34
Vert.x 3.4.0 introduced `tryComplete()` and `tryFail()`. These functions allow you to easily implement the original poster's suggested strategy to "check whether or not the Future is already completed in the catch block, and do "something else" if it's already completed.

**The important thing to remember is to never call `complete()` or `fail()` within a `catch` block if there is any possibility of the future being completed (and thus having its handlers called) within the associated `try` block.**

I also use `executeBlocking()` quite a bit with the following pattern.

```
Future<String> myFunction() {
    Future<Void> future = Future.future();

    getVertx().executeBlocking(unusedFuture -> {
        // ... code ...
        future.complete("Result"); // may call a handler which may throw
    }, future);

    return future;
}
```

The issue with this pattern is that `executeBlocking()` has a try/catch block embedded in it. If a handler attached to `future` throws an exception in response to `future.complete()` being called, the try/catch block in `executeBlocking()` will call `fail()` on the passed-in already-completed `future`.

The solution I've landed on is to do the following instead.

```
Future<String> myFunction() {
    Future<Void> future = Future.future();

    getVertx().executeBlocking(unusedFuture -> {
        // ... code ...
        future.complete("Result"); // may call a handler which may throw
    }, x -> {
        if (x.failed() && !future.tryFail(x.cause())) {
            // Log or rethrow x.cause()
        }
    });

    return future;
}
```

**Comment by vietj** [comment] 2020-08-16 10:38
@willisblackburn thanks for the heads-up on this, with Vert.x 4 you have a version of executeBlocking that returns the Future directly and any handler attached to the future will report the exception on the context instead.

**Comment by vietj** [comment] 2020-08-16 10:40
Also in Vert.x 4 you should be able to create futures that are attached to a Vert.x context (it exists but currently it is not exposed), such futures will fail as I mentioned, i.e they will report the downstream errors to the corresponding context instead. OTOH such future/promise cannot be statically created anymore, the shall be called on Vertx or Context instead

**Comment by vietj** [comment] 2020-08-18 15:53
closing this issue

**Closed** 2020-08-18 15:53 UTC

**Comment by austin-beer** [comment] 2021-07-21 16:15
Hi @vietj. When do you expect Vert.x 4 to support creating futures that are attached to a Vert.x context via a public API? Thanks.

**Comment by vietj** [comment] 2021-07-22 09:05
it is currently possible but the context needs to be cast to ContextInternal

**Comment by austin-beer** [comment] 2021-07-22 15:39
Okay, thanks @vietj. That makes sense, and I see that in the code now.

So according to the code (https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/future/FutureBase.java#L62), if a future is attached to a context but it's already running on that context when its listener is called, that listener will be called outside of a try/catch statement and so won't use that context's reportException() capability if it throws an exception. Is this behavior intentional or is it an oversight that should be reported as a Github issue?

**Comment by vietj** [comment] 2021-07-22 16:55
yes this is the intended behavior, when there is no context then it is
static and the exception should bubble up to be caught.

with Vert.x 4, users should reuse futures provided by Vert.x which are
normally attached to a context

**Comment by austin-beer** [comment] 2021-07-22 17:26
Except with the current code, even if there _is_ a context, the exception may still bubble up.

1. Future has a context, but the future is completed/failed on a different context:
    * Behavior: If a handler throws, it is given to context.reportException() and does not bubble up.
2. Future has a context, and the future is completed/failed on that context:
    * Behavior: If a handler throws, it bubbles up to whatever completed/failed the future.
3. Future does not have a context:
    * Behavior: If a handler throws, it bubbles up to whatever completed/failed the future.

I think the behavior of situation #2 should match #1. But currently it matches #3. This is due to the if() statement at https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/future/FutureBase.java#L50.

**Comment by vietj** [comment] 2021-07-22 20:03
that's right indeed

this should be tested more toroughly and fixed

**Comment by austin-beer** [comment] 2021-07-22 21:07
That makes sense. Do you want me to open a new Github issue for that?

**Comment by vietj** [comment] 2021-07-22 21:25
yes please!
