### ISSUE TITLE
NPE in SSLHelper

### ISSUE THREAD

**Issue by UglyHobbitFeet** [eclipse-vertx/vert.x#3341] opened 2020-03-22 15:44 UTC
I am trying to use AmqpClient with a keystore and am getting a nonhelpful message of 

SEVERE: Unhandled exception
```
io.vert.core.VertException: java.lang.NullPointerException
 at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:303)
 at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:478)

``````

What is happening is that the catch block inside createContext is swallowing the stacktrace of the NPE, so I have no idea where/how it's originating inside that method.

**Comment by vietj** [comment] 2020-03-23 07:09
do you have a reproducer ?

**Comment by UglyHobbitFeet** [comment] 2020-03-23 18:48
Unfortunately I do not. However the stacktrace shown should be enough to note that a NPE is being swallowed instead of logged (aka error.printStackTrace() or some equivalent logging). I would request that one or both of those be implemented in the catch block in that code.

**Comment by vietj** [comment] 2020-03-26 08:55
which version of Vert.x is it ?

**Comment by vietj** [comment] 2020-03-26 08:57
the excpetion is not swalled since the code does : `throw new VertxException(e)`, the nested NPE trace should be listed in your log

**Comment by UglyHobbitFeet** [comment] 2020-03-26 13:57
Unfortunately it's not. It's what is shown in the original post. I'm on
3.8.5

**Comment by vietj** [comment] 2020-03-26 14:49
I whish to get more info to reproduce the issue and fix it. right now we don't have enough information to understand the issue

**Comment by vietj** [comment] 2020-05-11 10:45
Closing for now until we get more info

**Closed** 2020-05-11 10:45 UTC
