### ISSUE TITLE
JsonParserImpl fails after resume

### ISSUE THREAD

**Issue by MikhailFokanov** [eclipse-vertx/vert.x#3886] opened 2021-04-08 14:36 UTC
### Version

4.0.0

It is regression bug, it works well with 3.9.4

### Context

We `pipeTo(WriteStream<T> dst)` method in JsonParser to implement batching of items, which are returned from web service. When the drainHandler is called, it calls `resume()` in JsonParserImpl. These methods are called at random time.

### Reproducer

* https://gist.github.com/MikhailFokanov/4137dcbaabbd033df0f081fca7101379

If the ROWS_NUMBER < 1000 it works well, otherwise fails.

### Steps to reproduce

1. Run the reproducer

**Comment by tsegismont** [comment] 2021-04-08 14:41
This might be a duplicate of https://github.com/eclipse-vertx/vert.x/issues/3822

@MikhailFokanov can you try with 4.0.3 please?

**Comment by MikhailFokanov** [comment] 2021-04-09 09:11
@tsegismont With 4.0.3 it still doen't work.

**Comment by adamdickmeiss** [comment] 2021-04-12 14:09
The code calls pause and resume from different threads than the Verticle running the parser. Is that safe?

**Comment by tsegismont** [comment] 2021-04-12 16:51
@adamdickmeiss you are right, JsonParser is not thread-safe and pause/resume should be invoked on the same thread that feeds the parser.

@MikhailFokanov I changed the test to this:

```java
        parser.handler(event -> {
            if (recordsCount.incrementAndGet() % 50 == 0) {
                System.out.println("Records returned so far: " + recordsCount.get());
            }
            vertx.setTimer(10, l -> {
              if (isPaused.get()) {
                isPaused.set(false);
                parser.resume();
              } else {
                isPaused.set(true);
                parser.pause();
              }
            });
        });
```

Then the test fails with a more meaningful message:

```
com.fasterxml.jackson.core.JsonParseException: Still have 95 undecoded bytes, should not call 'feedInput'
 at [Source: UNKNOWN; line: 1, column: 1931428]

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.json.async.NonBlockingJsonParser.feedInput(NonBlockingJsonParser.java:99)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handle(JsonParserImpl.java:199)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handle(JsonParserImpl.java:41)
	at io.vertx.ext.web.codec.impl.JsonStreamBodyCodec$1.write(JsonStreamBodyCodec.java:37)
	at io.vertx.ext.web.codec.impl.JsonStreamBodyCodec$1.write(JsonStreamBodyCodec.java:22)
	at io.vertx.ext.web.codec.impl.StreamingBodyCodec$1.write(StreamingBodyCodec.java:82)
	at io.vertx.ext.web.codec.impl.StreamingBodyCodec$1.write(StreamingBodyCodec.java:60)
	at io.vertx.core.streams.impl.PipeImpl.lambda$to$1(PipeImpl.java:81)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:239)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:378)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleChunk(Http1xClientConnection.java:581)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseChunk(Http1xClientConnection.java:782)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:680)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:647)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:153)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I believe we have a problem with `JsonParser` implementation and JsonParser codec in WebClient: the Jackson streaming parser must not be fed with more data unless `needsMoreInput` returns `true`.

**Closed** 2021-05-06 21:27 UTC
Labels: bug
