### ISSUE TITLE
Usage of verify() within `compose()`

### ISSUE THREAD

**Issue by komape** [eclipse-vertx/vert.x#4504] opened 2022-10-06 10:31 UTC
### Version

Version 4.1.8

### Context

For JUnit 5 tests I chain multiple `Future`s together with `compose()` and check each of them with JUnit assertions. At last, I do some assertions in `onComplete()`.

As suggested in the [Vert.x docs](https://vertx.io/docs/vertx-junit5/java/#_use_any_assertion_library) I used `verify()` to encapsulate the assertions. But this lead to weird behavior when it was used within `compose()`. Even tough an assertion failed within a `verify()` within a `compose()`, the following `compose()` calls were executed. I would have expected that they would be skipped as soon as one assertion fails.

I now removed all `verify()` from `compose()` and use it only in `onComplete()`. Now the tests work proper again.

I don't know if this is a bug or intended behavior. If this is intended, please add a hint to the documentation that `verify()` should not be used within `compose()` and instead assertions can be called directly. I couldn't find any hint. Otherwise I request a bug fix hereby.

### Do you have a reproducer?

Here's an example test:

```java
    @Test
    public void testVerify(VertxTestContext context) {
        Promise<Void> promise = Promise.promise();
        promise.complete();
        promise.future().compose(v -> {
            System.out.println("first compose 0");
            context.verify(() -> {
                System.out.println("first compose - first verify 0");
                fail("fail");
                System.out.println("first compose - first verify 1");
            });
            System.out.println("first compose 1");
            Promise<Void> p = Promise.promise();
            p.complete();
            return p.future();
        }).compose(v -> {
            System.out.println("second compose 0");
            Promise<Void> p = Promise.promise();
            p.complete();
            return p.future();
        }).onComplete(res -> {
            if (res.failed()) {
                System.out.println("first onComplete failed");
                context.failNow(res.cause());
            } else {
                System.out.println("first onComplete succeeded");
            }
        });
    }
```

The output of this test is:

```bash
first compose 0
first compose - first verify 0
first compose 1
second compose 0
first onComplete succeeded
```

But I expected it to be:

```bash
first compose 0
first compose - first verify 0
first onComplete failed
```

This is also the output of the test if `verify()` is removed.

**Comment by julianladisch** [comment] 2022-10-15 22:53
In your example `fail("fail")` correctly causes the `testVerify` method to fail, JUnit reports a failure for this method. Therefore this is not a bug.

VertxTestContext has strict checkpoints:
https://vertx.io/docs/apidocs/io/vertx/junit5/VertxTestContext.html#checkpoint--
If a strict checkpoint is flagged more often than expected the unit test fails. This can only be checked if a unit test continues to execute even if `completeNow()` has been called.
The async way of executions doesn't easily allow to stop all tasks after `completeNow()` or `failNow` has been called. Therefore no execution is stopped for ease of implementation and consistency.
The `fail("fail")` is handled by `failNow` and therefore doesn't need to stop the execution.

I suggest to close this issue as "Works as specified", "Not a bug".

**Comment by komape** [comment] 2022-11-03 13:47
@julianladisch Did you have chance to take a look on it?

**Comment by vietj** [comment] 2023-09-05 20:33
can you point out which issue reported this @julianladisch ?

**Comment by vietj** [comment] 2023-09-06 07:23
thanks

**Closed by vietj** 2023-09-06 07:23 UTC
Labels: bug
