### ISSUE TITLE
WebClient/HttpClient timeouts randomly

### ISSUE THREAD

**Issue by diegomoreira001** [eclipse-vertx/vert.x#3664] opened 2020-11-23 14:38 UTC
### Version

3.9.4; 4.0.0.CR1

### Context

We've built a "reverse proxy" that routes the incoming requests to a cluster of backend services based on a request header (X-Target-Host & Port). 

The code is pretty simple and straightforward. We created an HttpServer that receives the connections on port 8080, and then a request handler with a single WebClient instance creates a new request and forwards it to the backend service.

**On Mac OS:**
When testing locally with jmeter, whenever we reach a total 8171/8170 requests, the WebClient timeouts for the in-flight requests. After a few timeouts it recovers and works again for another 8000 requests or so.

The backend service is mocked. We mocked it by creating another verticle, and we also tested with "mockserver".

**On Windows:**
It seems to work just fine.

**On our production env on debian:slim:**
In here we are using a real backend service. We noticed that **these timeouts occur after just a 30, 40 requests**. It seems that the error is more frequent when the response time of the backend service is higher. 

**What we tried so far:**
We originally wrote the code with Vertx 3.9.4. We migrated to 4.0.0.CR1 but the error persists.
We also reimplemented it several times using Webclient and HttpClient. 
We also wrote it using just callbacks, futures and promises.
We tried deploying 3 instances of our verticle instead of 1.
We tried with jdk8 and 11.
Tried on two different macs, and the same error occurs.
We extended the connection pools.
Tried with native transport.
Played a bit with keep-alive, notcpdelay, etc.
We wrote the entire buffer to the requests. We tried streaming. The behaviour is always the same.

### Do you have a reproducer?

Yes

* Link to github project/gist
https://github.com/diegomoreira001/reproducer-webclient-timeout

Inside the project there is a .jmx file with the jmeter test prepared.
This is a convoluted version of the code after many trials and errors. We wrapped everything inside a circuit breaker, we also tried executeBlocking, we tried creating one instance of webclient per request, etc...

Even with the simplest version of the code (without circuit breaker, without executeBlocking, etc.), we got the same error.
### Steps to reproduce

**On Mac:**
1. Compile & package the project: mvn clean package:
2. Run the fat jar:
java -jar ./target/whatsapp-router-1.0-SNAPSHOT-fat.jar
3. Run jmeter, import the project .jmx file, and press play (or use the batch version).
It is currently configured with 2 threads and 5000 loops (it should die after 8170 requests aprox.)

There is also a JFR file included in the project generated with JDK8.

**Comment by diegomoreira001** [comment] 2020-11-23 15:51
Similar if not the same as #3399

**Comment by vietj** [comment] 2020-11-24 07:27
I closed the other issue because it was old, we'll keep this one since it has a reproducer too.

**Comment by vietj** [comment] 2020-11-24 07:28
Can you elaborate what you mean by randomly ? it is not clear what we should observe as issue.

**Comment by diegomoreira001** [comment] 2020-11-24 13:20
Well, randomly may not be the best word to describe it. 

What’s happening is we get timeouts on the WebClient after a few requests.

When running locally and the webclient connects to a local mocked backend, it starts throwing timeouts after 817x requests.

On prod, this happens after 30 or 40 requests. (Latency between the app and the service is 50ms on average and worst case 150ms)

A timeout on the webclient would indicate the remote service is non-responsive, but this is not the case. When this error occurs, we confirmed using wireshark and tcpdump that there is no incoming traffic to the service.

Also, this happens with any remote service. We tried against a mocked backend, against a real one, against stackoverflow webpage, etc.

So we believe there is some queuing happening on the webclient (not sure if on the request or the response) and after a while it is not able to catch up and something breaks. Higher latencies seem to make things worse.

**Comment by vietj** [comment] 2020-11-24 13:44
I'll have a look as soon as possible

**Comment by vietj** [comment] 2020-11-24 13:44
I assigned to 4.0 as reminder

**Comment by diegomoreira001** [comment] 2020-11-24 14:03
Sure, let me know if I can be of any help.

**Comment by vietj** [comment] 2020-11-26 14:57
@diegomoreira001 not dismissing this issue : have you tried using https://github.com/vietj/vertx-http-proxy ?

this has been recently rebased on Vert.x 4 and it will be part of Vert.x 4.1

**Comment by vietj** [comment] 2020-11-26 15:00
@diegomoreira001 could you provide us for testing the most simple version that fails ? my point is that it will be easier for us to find out the issue

**Comment by diegomoreira001** [comment] 2020-11-27 13:22
@vietj sorry for the delay... 

sure! I'll upload another version today.

regarding vertx-http-proxy, I'll give it a try over the weekend.

**Closed** 2021-06-03 09:13 UTC
Labels: bug

**Comment by gaston-haro** [comment] 2021-12-03 15:52
So what happened? Issues should not be closed without a reason.
