### ISSUE TITLE
Verticle still serves event bus events after undeployment complete

### ISSUE THREAD

**Issue by FDoKE** [eclipse-vertx/vert.x#4657] opened 2023-03-31 05:26 UTC
### Version

4.4.1

### Context

Verticles serve event bus events even after undeployed.
This happens when on verticle `start(Promise)` method active eventloop thread switched to some other thread.
I don't know if that's expected behaivor, but result looks like a bug.

### Do you have a reproducer?
2 tests that shows this bug and correct one without an issue.
https://pastebin.com/Tzi5GGAq

### Steps to reproduce

1. Create a verticle which overrides start(Promise) make consumers and handle start promise in another thread.
2. Fire event, it processes.
3. Undeploy verticle and wait for undeployment
4. Fire event - it still processes

### Extra
I don't know if that intentional. But looks like you should switch back on eventloop thread after start promise is handled.
Docs not showing that it can cause that type of a problem.

**Comment by FDoKE** [comment] 2023-03-31 10:00
Also additionally I wil say that it breaks all other verticles deployments too. (consumers even on simple verticles not undeployed too)

**Comment by gaol** [comment] 2023-04-24 05:51
@FDoKE from what I read in your tests, the consumer was created from a non vertx thread, which makes the consumer not bound to the verticle context, which means when the verticle gets undeployed, the consumer does not get unregistered automatically. So there are 2 options to make your tests pass:

- Create the consumer in the verticle context: `context.runOnContext(h -> vertx.eventBus().consumer("test", v -> {xxx}));`
- Or record the MessageConsumer in the verticle, and call unregister() explicitly in the verticle stop method.

**Comment by tsegismont** [comment] 2023-05-02 19:59
Thank you @gaol , closing as not a bug

**Closed by tsegismont** 2023-05-02 19:59 UTC
Labels: invalid
