### ISSUE TITLE
"Response has already been written" using Vertx rx Http and request is cancelled by the client

### ISSUE THREAD

**Issue by jhaeyaert** [eclipse-vertx/vert.x#4479] opened 2022-09-09 09:50 UTC
### Version

vertx 4.2.7
vertx-rx-java2 4.2.7

### Context

At Gravitee, we are relying massively on vertx. We discovered what appears to be a bug when using vert-rx http.
When we make an http request that returns a flow of multiple buffers and the client stop the connection, vertx throws the following exception:

```
10:32:29.689 [vert.x-eventloop-thread-1] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.Http1xServerResponse.checkValid(Http1xServerResponse.java:675)
	at io.vertx.core.http.impl.Http1xServerResponse.writeQueueFull(Http1xServerResponse.java:274)
	at io.vertx.core.streams.impl.PipeImpl.lambda$to$1(PipeImpl.java:82)
	at io.vertx.reactivex.impl.ReadStreamSubscriber.checkStatus(ReadStreamSubscriber.java:166)
	at io.vertx.reactivex.impl.ReadStreamSubscriber.onNext(ReadStreamSubscriber.java:220)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorReturn$OnErrorReturnSubscriber.onNext(FlowableOnErrorReturn.java:50)
	at io.reactivex.internal.operators.flowable.FlowableConcatArray$ConcatArraySubscriber.onNext(FlowableConcatArray.java:77)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ImmediateThinScheduler$ImmediateThinWorker.schedule(ImmediateThinScheduler.java:89)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.trySchedule(FlowableObserveOn.java:166)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.onNext(FlowableObserveOn.java:117)
	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
	at io.reactivex.internal.operators.flowable.FlowableDelay$DelaySubscriber$OnNext.run(FlowableDelay.java:114)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.run(ContextScheduler.java:184)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Digging a bit, we found that when using `response.rxSend(Flowable<Buffer>)`, the provided source of buffer is never cancelled while the subscription on the completable is disposed.

The source continues to produce buffers while the connection is already close. Any attempt to write to the connection results in the above error.

### Do you have a reproducer?

I managed to simply reproduce the behavior showing that the cancellation is not propagated using the following simple test that shows that the source buffer flow is not well cancelled as it should (and so does not avoid to produce new buffer that will end in error when trying to write them to the close connection).

```java
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.reactivex.Completable;
import io.reactivex.Flowable;
import io.reactivex.observers.TestObserver;
import io.vertx.codegen.annotations.Nullable;
import io.vertx.core.AsyncResult;
import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.streams.ReadStream;
import io.vertx.core.streams.WriteStream;
import io.vertx.reactivex.impl.AsyncResultCompletable;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.Test;

/**
 * @author Jeoffrey HAEYAERT (jeoffrey.haeyaert at graviteesource.com)
 * @author GraviteeSource Team
 */
public class PipeSourceNotCancelledTest {

    @Test
    void test() {
        final AtomicBoolean bodyDisposed = new AtomicBoolean(false);
        final AtomicBoolean completableDisposed = new AtomicBoolean(false);

        // Body source that creates buffers slowly (each second).
        final Flowable<Buffer> body = Flowable
            .interval(1000, TimeUnit.MILLISECONDS)
            .map(i -> Buffer.buffer("buffer " + i))
            .doOnCancel(() -> {
                bodyDisposed.set(true);
                System.out.println("Body source has been cancelled :-)");
            });

        final Completable completable = AsyncResultCompletable.toCompletable(handler ->
            send(io.vertx.reactivex.impl.ReadStreamSubscriber.asReadStream(body, obj -> obj).resume(), handler)
        );

        final TestObserver<Void> obs = completable
            .doOnDispose(() -> {
                completableDisposed.set(true);
                System.out.println("Completable has been disposed");
            })
            .test();

        obs.awaitCount(5); // Consume only 5 buffers.
        obs.cancel(); // Then cancel.
        obs.assertNotComplete();

        // Completable should have been disposed.
        assertTrue(completableDisposed.get());

        // Body source should have been cancelled. <-- Fails
        assertTrue(bodyDisposed.get());
    }

    void send(ReadStream<Buffer> body, Handler<AsyncResult<Void>> handler) {
        body.pipeTo(new FakeWriteStream(), handler);
    }

    static class FakeAsyncResult implements AsyncResult<Void> {

        @Override
        public Void result() {
            return null;
        }

        @Override
        public Throwable cause() {
            return null;
        }

        @Override
        public boolean succeeded() {
            return true;
        }

        @Override
        public boolean failed() {
            return false;
        }
    }

    static class FakeWriteStream implements WriteStream<Buffer> {

        @Override
        public WriteStream<Buffer> exceptionHandler(Handler<Throwable> handler) {
            return this;
        }

        @Override
        public Future<Void> write(Buffer data) {
            System.out.println("write " + data.toString());
            return Future.succeededFuture();
        }

        @Override
        public void write(Buffer data, Handler<AsyncResult<Void>> handler) {
            System.out.println("write " + data.toString());
            handler.handle(new FakeAsyncResult());
        }

        @Override
        public void end(Handler<AsyncResult<Void>> handler) {
            handler.handle(new FakeAsyncResult());
        }

        @Override
        public WriteStream<Buffer> setWriteQueueMaxSize(int maxSize) {
            return this;
        }

        @Override
        public boolean writeQueueFull() {
            return false;
        }

        @Override
        public WriteStream<Buffer> drainHandler(@Nullable Handler<Void> handler) {
            return this;
        }
    }
}
```

I'm wondering if there is a way to propagate the cancellation signal to the source ?

Thank for your help.

### Steps to reproduce

Run the provided junit test.

### Extra

* N/A

**Comment by vietj** [comment] 2022-09-09 14:22
it is not clear whether it is an RX issue or a vertx-core issue

**Comment by vietj** [comment] 2022-09-09 14:24
perhaps we could try when this fails to null out the fields of the ReadStream (e.g handler) so that it triggers an RX unsubscription (that's what vertx-rx does when the field is set to null)

**Comment by vietj** [comment] 2022-09-09 14:45
Actually send() uses pipe under the hood, so it seems to be a pipe issue after all :-)

**Comment by vietj** [comment] 2022-09-09 14:51
Do you mind providing a reproducer with an HTTP server ? that would help to figure out better what happens in practice and how we could solve it.

**Comment by vietj** [comment] 2022-09-09 15:01
In practice the pipe operation that performs the write should fail (because the stream is not writable) and "cancel" the read stream (set null handler). In this case it does not happen because the Completable unsubscription cannot be handled from `AsyncResultCompletable.toCompletable` and close the pipe, in short to be accurate the reproducer:

```java
    final Completable completable = AsyncResultCompletable.toCompletable(handler ->
      send(io.vertx.reactivex.impl.ReadStreamSubscriber.asReadStream(body, obj -> obj).resume(), handler)
    );
```

should take the pipe (in the send method) and close it when something goes bad.

That's why I'd like a reproducer of the case you are hitting in practice.

**Comment by jhaeyaert** [comment] 2022-09-09 15:19
Ok let me some time to ty to provide a complete test involving the http server but IMHO the issue seems to be located `AsyncResultCompletable` which does not seem to do anything regarding the source when the `dispose()` method is triggered (because it just can't). 

So, from what I understood, the cancel signal is not "directly" propagated to the source but instead it is managed later (in a way I can't figure out 🧐) after the connection is closed. This does not prevent the source to generate new buffers the `WriteStream` will then try to write. The error occurs at the moment where the `checkValid()` is made on the response (I did the test in HTTP1 and HTTP2).

I found a workaround by basically doing this but it's not something we'd like to keep indefinitely:

```java
          final AtomicReference<Subscription> subscriptionRef = new AtomicReference<>();
         
          return nativeResponse
                        .rxSend(
                            chunks().doOnSubscribe(subscriptionRef::set))
                        )
                        .doOnDispose(() -> subscriptionRef.get().cancel());
```

So if something dispose the subscription made on the return `Completable`, I am able to dispose the subscription made on my  `Flowable<Buffer>` by me self and then everything is working well with no exception anymore.

Cheers

**Comment by jhaeyaert** [comment] 2022-09-11 09:56
Hi @vietj 
Here is a reproducible case for the mentioned issue: https://github.com/jhaeyaert/rx-cancel-issue

Hope it'll help.

**Comment by vietj** [comment] 2022-09-12 07:31
thanks.

**Comment by vietj** [comment] 2022-09-12 10:14
@jhaeyaert here is a fix for the issue, classes adapting a `Publisher` to a `ReadStream` where not handling cancellation

**Comment by jhaeyaert** [comment] 2022-09-12 10:21
Hello @vietj 

I'm maybe missing something, which fix are you talking about ? Perhaps you forgot a link ? 🧐

**Comment by vietj** [comment] 2022-09-12 11:57
here we are :-) https://github.com/vert-x3/vertx-rx/pull/285

**Comment by vietj** [comment] 2022-09-14 15:19
fixed in vertx-rx

**Closed by vietj** 2022-09-14 15:19 UTC
Labels: bug

**Comment by jhaeyaert** [comment] 2022-09-16 05:15
Many thanks @vietj
